package com.plm.dao;

import com.plm.model.PostInfo;
import com.plm.model.PostInfoExample;
import java.util.List;

public interface PostInfoMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table post_info
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	int deleteByPrimaryKey(Integer piId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table post_info
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	int insert(PostInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table post_info
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	int insertSelective(PostInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table post_info
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	List<PostInfo> selectByExample(PostInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table post_info
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	PostInfo selectByPrimaryKey(Integer piId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table post_info
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	int updateByPrimaryKeySelective(PostInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table post_info
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	int updateByPrimaryKey(PostInfo record);
}