package com.plm.dao;

import com.plm.model.ProjectBaseView;
import com.plm.model.ProjectBaseViewExample;
import java.util.List;

public interface ProjectBaseViewMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table project_base_view
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	int insert(ProjectBaseView record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table project_base_view
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	int insertSelective(ProjectBaseView record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table project_base_view
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	List<ProjectBaseView> selectByExample(ProjectBaseViewExample example);

	List<ProjectBaseView> selectHasGroup(ProjectBaseViewExample example);
}