package com.plm.dao;

import com.plm.model.ProjectBase;
import com.plm.model.ProjectBaseExample;
import java.util.List;

public interface ProjectBaseMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table project_base
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	int deleteByPrimaryKey(Integer pbId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table project_base
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	int insert(ProjectBase record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table project_base
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	int insertSelective(ProjectBase record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table project_base
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	List<ProjectBase> selectByExample(ProjectBaseExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table project_base
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	ProjectBase selectByPrimaryKey(Integer pbId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table project_base
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	int updateByPrimaryKeySelective(ProjectBase record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table project_base
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	int updateByPrimaryKey(ProjectBase record);
}