package com.plm.dao;

import com.plm.model.ProjectPlan;
import com.plm.model.ProjectPlanExample;
import java.util.List;

public interface ProjectPlanMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table project_plan
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	int deleteByPrimaryKey(Integer ppId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table project_plan
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	int insert(ProjectPlan record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table project_plan
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	int insertSelective(ProjectPlan record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table project_plan
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	List<ProjectPlan> selectByExample(ProjectPlanExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table project_plan
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	ProjectPlan selectByPrimaryKey(Integer ppId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table project_plan
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	int updateByPrimaryKeySelective(ProjectPlan record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table project_plan
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	int updateByPrimaryKey(ProjectPlan record);
}