package com.plm.dao;

import com.plm.model.ProjectFundsView;
import com.plm.model.ProjectFundsViewExample;
import java.util.List;

public interface ProjectFundsViewMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table project_funds_view
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	int insert(ProjectFundsView record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table project_funds_view
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	int insertSelective(ProjectFundsView record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table project_funds_view
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	List<ProjectFundsView> selectByExample(ProjectFundsViewExample example);

	List<ProjectFundsView> selectHasGroup(ProjectFundsViewExample example);
}