package com.plm.dao;

import com.plm.model.ProjectUser;
import com.plm.model.ProjectUserExample;
import java.util.List;

public interface ProjectUserMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table project_user
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	int deleteByPrimaryKey(Integer puId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table project_user
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	int insert(ProjectUser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table project_user
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	int insertSelective(ProjectUser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table project_user
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	List<ProjectUser> selectByExample(ProjectUserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table project_user
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	ProjectUser selectByPrimaryKey(Integer puId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table project_user
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	int updateByPrimaryKeySelective(ProjectUser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table project_user
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	int updateByPrimaryKey(ProjectUser record);
}