package com.plm.dao;

import com.plm.model.SiteFileInfo;
import com.plm.model.SiteFileInfoExample;
import java.util.List;

public interface SiteFileInfoMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table site_file_info
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	int deleteByPrimaryKey(Integer sfId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table site_file_info
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	int insert(SiteFileInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table site_file_info
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	int insertSelective(SiteFileInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table site_file_info
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	List<SiteFileInfo> selectByExample(SiteFileInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table site_file_info
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	SiteFileInfo selectByPrimaryKey(Integer sfId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table site_file_info
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	int updateByPrimaryKeySelective(SiteFileInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table site_file_info
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	int updateByPrimaryKey(SiteFileInfo record);
}