package com.plm.dao;

import com.plm.model.UserMessage;
import com.plm.model.UserMessageExample;
import java.util.List;

public interface UserMessageMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_message
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	int deleteByPrimaryKey(Integer umId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_message
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	int insert(UserMessage record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_message
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	int insertSelective(UserMessage record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_message
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	List<UserMessage> selectByExample(UserMessageExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_message
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	UserMessage selectByPrimaryKey(Integer umId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_message
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	int updateByPrimaryKeySelective(UserMessage record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_message
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	int updateByPrimaryKey(UserMessage record);
}