package com.plm.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class PostViewExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table post_view
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table post_view
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table post_view
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table post_view
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public PostViewExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table post_view
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table post_view
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table post_view
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table post_view
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table post_view
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table post_view
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table post_view
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table post_view
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table post_view
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table post_view
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table post_view
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andPiTitleIsNull() {
			addCriterion("PI_TITLE is null");
			return (Criteria) this;
		}

		public Criteria andPiTitleIsNotNull() {
			addCriterion("PI_TITLE is not null");
			return (Criteria) this;
		}

		public Criteria andPiTitleEqualTo(String value) {
			addCriterion("PI_TITLE =", value, "piTitle");
			return (Criteria) this;
		}

		public Criteria andPiTitleNotEqualTo(String value) {
			addCriterion("PI_TITLE <>", value, "piTitle");
			return (Criteria) this;
		}

		public Criteria andPiTitleGreaterThan(String value) {
			addCriterion("PI_TITLE >", value, "piTitle");
			return (Criteria) this;
		}

		public Criteria andPiTitleGreaterThanOrEqualTo(String value) {
			addCriterion("PI_TITLE >=", value, "piTitle");
			return (Criteria) this;
		}

		public Criteria andPiTitleLessThan(String value) {
			addCriterion("PI_TITLE <", value, "piTitle");
			return (Criteria) this;
		}

		public Criteria andPiTitleLessThanOrEqualTo(String value) {
			addCriterion("PI_TITLE <=", value, "piTitle");
			return (Criteria) this;
		}

		public Criteria andPiTitleLike(String value) {
			addCriterion("PI_TITLE like", value, "piTitle");
			return (Criteria) this;
		}

		public Criteria andPiTitleNotLike(String value) {
			addCriterion("PI_TITLE not like", value, "piTitle");
			return (Criteria) this;
		}

		public Criteria andPiTitleIn(List<String> values) {
			addCriterion("PI_TITLE in", values, "piTitle");
			return (Criteria) this;
		}

		public Criteria andPiTitleNotIn(List<String> values) {
			addCriterion("PI_TITLE not in", values, "piTitle");
			return (Criteria) this;
		}

		public Criteria andPiTitleBetween(String value1, String value2) {
			addCriterion("PI_TITLE between", value1, value2, "piTitle");
			return (Criteria) this;
		}

		public Criteria andPiTitleNotBetween(String value1, String value2) {
			addCriterion("PI_TITLE not between", value1, value2, "piTitle");
			return (Criteria) this;
		}

		public Criteria andPiContentIsNull() {
			addCriterion("PI_CONTENT is null");
			return (Criteria) this;
		}

		public Criteria andPiContentIsNotNull() {
			addCriterion("PI_CONTENT is not null");
			return (Criteria) this;
		}

		public Criteria andPiContentEqualTo(String value) {
			addCriterion("PI_CONTENT =", value, "piContent");
			return (Criteria) this;
		}

		public Criteria andPiContentNotEqualTo(String value) {
			addCriterion("PI_CONTENT <>", value, "piContent");
			return (Criteria) this;
		}

		public Criteria andPiContentGreaterThan(String value) {
			addCriterion("PI_CONTENT >", value, "piContent");
			return (Criteria) this;
		}

		public Criteria andPiContentGreaterThanOrEqualTo(String value) {
			addCriterion("PI_CONTENT >=", value, "piContent");
			return (Criteria) this;
		}

		public Criteria andPiContentLessThan(String value) {
			addCriterion("PI_CONTENT <", value, "piContent");
			return (Criteria) this;
		}

		public Criteria andPiContentLessThanOrEqualTo(String value) {
			addCriterion("PI_CONTENT <=", value, "piContent");
			return (Criteria) this;
		}

		public Criteria andPiContentLike(String value) {
			addCriterion("PI_CONTENT like", value, "piContent");
			return (Criteria) this;
		}

		public Criteria andPiContentNotLike(String value) {
			addCriterion("PI_CONTENT not like", value, "piContent");
			return (Criteria) this;
		}

		public Criteria andPiContentIn(List<String> values) {
			addCriterion("PI_CONTENT in", values, "piContent");
			return (Criteria) this;
		}

		public Criteria andPiContentNotIn(List<String> values) {
			addCriterion("PI_CONTENT not in", values, "piContent");
			return (Criteria) this;
		}

		public Criteria andPiContentBetween(String value1, String value2) {
			addCriterion("PI_CONTENT between", value1, value2, "piContent");
			return (Criteria) this;
		}

		public Criteria andPiContentNotBetween(String value1, String value2) {
			addCriterion("PI_CONTENT not between", value1, value2, "piContent");
			return (Criteria) this;
		}

		public Criteria andHasAccessoryIsNull() {
			addCriterion("HAS_ACCESSORY is null");
			return (Criteria) this;
		}

		public Criteria andHasAccessoryIsNotNull() {
			addCriterion("HAS_ACCESSORY is not null");
			return (Criteria) this;
		}

		public Criteria andHasAccessoryEqualTo(Integer value) {
			addCriterion("HAS_ACCESSORY =", value, "hasAccessory");
			return (Criteria) this;
		}

		public Criteria andHasAccessoryNotEqualTo(Integer value) {
			addCriterion("HAS_ACCESSORY <>", value, "hasAccessory");
			return (Criteria) this;
		}

		public Criteria andHasAccessoryGreaterThan(Integer value) {
			addCriterion("HAS_ACCESSORY >", value, "hasAccessory");
			return (Criteria) this;
		}

		public Criteria andHasAccessoryGreaterThanOrEqualTo(Integer value) {
			addCriterion("HAS_ACCESSORY >=", value, "hasAccessory");
			return (Criteria) this;
		}

		public Criteria andHasAccessoryLessThan(Integer value) {
			addCriterion("HAS_ACCESSORY <", value, "hasAccessory");
			return (Criteria) this;
		}

		public Criteria andHasAccessoryLessThanOrEqualTo(Integer value) {
			addCriterion("HAS_ACCESSORY <=", value, "hasAccessory");
			return (Criteria) this;
		}

		public Criteria andHasAccessoryIn(List<Integer> values) {
			addCriterion("HAS_ACCESSORY in", values, "hasAccessory");
			return (Criteria) this;
		}

		public Criteria andHasAccessoryNotIn(List<Integer> values) {
			addCriterion("HAS_ACCESSORY not in", values, "hasAccessory");
			return (Criteria) this;
		}

		public Criteria andHasAccessoryBetween(Integer value1, Integer value2) {
			addCriterion("HAS_ACCESSORY between", value1, value2, "hasAccessory");
			return (Criteria) this;
		}

		public Criteria andHasAccessoryNotBetween(Integer value1, Integer value2) {
			addCriterion("HAS_ACCESSORY not between", value1, value2, "hasAccessory");
			return (Criteria) this;
		}

		public Criteria andPostTimeIsNull() {
			addCriterion("POST_TIME is null");
			return (Criteria) this;
		}

		public Criteria andPostTimeIsNotNull() {
			addCriterion("POST_TIME is not null");
			return (Criteria) this;
		}

		public Criteria andPostTimeEqualTo(Date value) {
			addCriterion("POST_TIME =", value, "postTime");
			return (Criteria) this;
		}

		public Criteria andPostTimeNotEqualTo(Date value) {
			addCriterion("POST_TIME <>", value, "postTime");
			return (Criteria) this;
		}

		public Criteria andPostTimeGreaterThan(Date value) {
			addCriterion("POST_TIME >", value, "postTime");
			return (Criteria) this;
		}

		public Criteria andPostTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("POST_TIME >=", value, "postTime");
			return (Criteria) this;
		}

		public Criteria andPostTimeLessThan(Date value) {
			addCriterion("POST_TIME <", value, "postTime");
			return (Criteria) this;
		}

		public Criteria andPostTimeLessThanOrEqualTo(Date value) {
			addCriterion("POST_TIME <=", value, "postTime");
			return (Criteria) this;
		}

		public Criteria andPostTimeIn(List<Date> values) {
			addCriterion("POST_TIME in", values, "postTime");
			return (Criteria) this;
		}

		public Criteria andPostTimeNotIn(List<Date> values) {
			addCriterion("POST_TIME not in", values, "postTime");
			return (Criteria) this;
		}

		public Criteria andPostTimeBetween(Date value1, Date value2) {
			addCriterion("POST_TIME between", value1, value2, "postTime");
			return (Criteria) this;
		}

		public Criteria andPostTimeNotBetween(Date value1, Date value2) {
			addCriterion("POST_TIME not between", value1, value2, "postTime");
			return (Criteria) this;
		}

		public Criteria andPostEditTimeIsNull() {
			addCriterion("POST_EDIT_TIME is null");
			return (Criteria) this;
		}

		public Criteria andPostEditTimeIsNotNull() {
			addCriterion("POST_EDIT_TIME is not null");
			return (Criteria) this;
		}

		public Criteria andPostEditTimeEqualTo(Date value) {
			addCriterion("POST_EDIT_TIME =", value, "postEditTime");
			return (Criteria) this;
		}

		public Criteria andPostEditTimeNotEqualTo(Date value) {
			addCriterion("POST_EDIT_TIME <>", value, "postEditTime");
			return (Criteria) this;
		}

		public Criteria andPostEditTimeGreaterThan(Date value) {
			addCriterion("POST_EDIT_TIME >", value, "postEditTime");
			return (Criteria) this;
		}

		public Criteria andPostEditTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("POST_EDIT_TIME >=", value, "postEditTime");
			return (Criteria) this;
		}

		public Criteria andPostEditTimeLessThan(Date value) {
			addCriterion("POST_EDIT_TIME <", value, "postEditTime");
			return (Criteria) this;
		}

		public Criteria andPostEditTimeLessThanOrEqualTo(Date value) {
			addCriterion("POST_EDIT_TIME <=", value, "postEditTime");
			return (Criteria) this;
		}

		public Criteria andPostEditTimeIn(List<Date> values) {
			addCriterion("POST_EDIT_TIME in", values, "postEditTime");
			return (Criteria) this;
		}

		public Criteria andPostEditTimeNotIn(List<Date> values) {
			addCriterion("POST_EDIT_TIME not in", values, "postEditTime");
			return (Criteria) this;
		}

		public Criteria andPostEditTimeBetween(Date value1, Date value2) {
			addCriterion("POST_EDIT_TIME between", value1, value2, "postEditTime");
			return (Criteria) this;
		}

		public Criteria andPostEditTimeNotBetween(Date value1, Date value2) {
			addCriterion("POST_EDIT_TIME not between", value1, value2, "postEditTime");
			return (Criteria) this;
		}

		public Criteria andUNameIsNull() {
			addCriterion("U_NAME is null");
			return (Criteria) this;
		}

		public Criteria andUNameIsNotNull() {
			addCriterion("U_NAME is not null");
			return (Criteria) this;
		}

		public Criteria andUNameEqualTo(String value) {
			addCriterion("U_NAME =", value, "uName");
			return (Criteria) this;
		}

		public Criteria andUNameNotEqualTo(String value) {
			addCriterion("U_NAME <>", value, "uName");
			return (Criteria) this;
		}

		public Criteria andUNameGreaterThan(String value) {
			addCriterion("U_NAME >", value, "uName");
			return (Criteria) this;
		}

		public Criteria andUNameGreaterThanOrEqualTo(String value) {
			addCriterion("U_NAME >=", value, "uName");
			return (Criteria) this;
		}

		public Criteria andUNameLessThan(String value) {
			addCriterion("U_NAME <", value, "uName");
			return (Criteria) this;
		}

		public Criteria andUNameLessThanOrEqualTo(String value) {
			addCriterion("U_NAME <=", value, "uName");
			return (Criteria) this;
		}

		public Criteria andUNameLike(String value) {
			addCriterion("U_NAME like", value, "uName");
			return (Criteria) this;
		}

		public Criteria andUNameNotLike(String value) {
			addCriterion("U_NAME not like", value, "uName");
			return (Criteria) this;
		}

		public Criteria andUNameIn(List<String> values) {
			addCriterion("U_NAME in", values, "uName");
			return (Criteria) this;
		}

		public Criteria andUNameNotIn(List<String> values) {
			addCriterion("U_NAME not in", values, "uName");
			return (Criteria) this;
		}

		public Criteria andUNameBetween(String value1, String value2) {
			addCriterion("U_NAME between", value1, value2, "uName");
			return (Criteria) this;
		}

		public Criteria andUNameNotBetween(String value1, String value2) {
			addCriterion("U_NAME not between", value1, value2, "uName");
			return (Criteria) this;
		}

		public Criteria andURealnameIsNull() {
			addCriterion("U_REALNAME is null");
			return (Criteria) this;
		}

		public Criteria andURealnameIsNotNull() {
			addCriterion("U_REALNAME is not null");
			return (Criteria) this;
		}

		public Criteria andURealnameEqualTo(String value) {
			addCriterion("U_REALNAME =", value, "uRealname");
			return (Criteria) this;
		}

		public Criteria andURealnameNotEqualTo(String value) {
			addCriterion("U_REALNAME <>", value, "uRealname");
			return (Criteria) this;
		}

		public Criteria andURealnameGreaterThan(String value) {
			addCriterion("U_REALNAME >", value, "uRealname");
			return (Criteria) this;
		}

		public Criteria andURealnameGreaterThanOrEqualTo(String value) {
			addCriterion("U_REALNAME >=", value, "uRealname");
			return (Criteria) this;
		}

		public Criteria andURealnameLessThan(String value) {
			addCriterion("U_REALNAME <", value, "uRealname");
			return (Criteria) this;
		}

		public Criteria andURealnameLessThanOrEqualTo(String value) {
			addCriterion("U_REALNAME <=", value, "uRealname");
			return (Criteria) this;
		}

		public Criteria andURealnameLike(String value) {
			addCriterion("U_REALNAME like", value, "uRealname");
			return (Criteria) this;
		}

		public Criteria andURealnameNotLike(String value) {
			addCriterion("U_REALNAME not like", value, "uRealname");
			return (Criteria) this;
		}

		public Criteria andURealnameIn(List<String> values) {
			addCriterion("U_REALNAME in", values, "uRealname");
			return (Criteria) this;
		}

		public Criteria andURealnameNotIn(List<String> values) {
			addCriterion("U_REALNAME not in", values, "uRealname");
			return (Criteria) this;
		}

		public Criteria andURealnameBetween(String value1, String value2) {
			addCriterion("U_REALNAME between", value1, value2, "uRealname");
			return (Criteria) this;
		}

		public Criteria andURealnameNotBetween(String value1, String value2) {
			addCriterion("U_REALNAME not between", value1, value2, "uRealname");
			return (Criteria) this;
		}

		public Criteria andRoleIsNull() {
			addCriterion("ROLE is null");
			return (Criteria) this;
		}

		public Criteria andRoleIsNotNull() {
			addCriterion("ROLE is not null");
			return (Criteria) this;
		}

		public Criteria andRoleEqualTo(Integer value) {
			addCriterion("ROLE =", value, "role");
			return (Criteria) this;
		}

		public Criteria andRoleNotEqualTo(Integer value) {
			addCriterion("ROLE <>", value, "role");
			return (Criteria) this;
		}

		public Criteria andRoleGreaterThan(Integer value) {
			addCriterion("ROLE >", value, "role");
			return (Criteria) this;
		}

		public Criteria andRoleGreaterThanOrEqualTo(Integer value) {
			addCriterion("ROLE >=", value, "role");
			return (Criteria) this;
		}

		public Criteria andRoleLessThan(Integer value) {
			addCriterion("ROLE <", value, "role");
			return (Criteria) this;
		}

		public Criteria andRoleLessThanOrEqualTo(Integer value) {
			addCriterion("ROLE <=", value, "role");
			return (Criteria) this;
		}

		public Criteria andRoleIn(List<Integer> values) {
			addCriterion("ROLE in", values, "role");
			return (Criteria) this;
		}

		public Criteria andRoleNotIn(List<Integer> values) {
			addCriterion("ROLE not in", values, "role");
			return (Criteria) this;
		}

		public Criteria andRoleBetween(Integer value1, Integer value2) {
			addCriterion("ROLE between", value1, value2, "role");
			return (Criteria) this;
		}

		public Criteria andRoleNotBetween(Integer value1, Integer value2) {
			addCriterion("ROLE not between", value1, value2, "role");
			return (Criteria) this;
		}

		public Criteria andPiIdIsNull() {
			addCriterion("PI_ID is null");
			return (Criteria) this;
		}

		public Criteria andPiIdIsNotNull() {
			addCriterion("PI_ID is not null");
			return (Criteria) this;
		}

		public Criteria andPiIdEqualTo(Integer value) {
			addCriterion("PI_ID =", value, "piId");
			return (Criteria) this;
		}

		public Criteria andPiIdNotEqualTo(Integer value) {
			addCriterion("PI_ID <>", value, "piId");
			return (Criteria) this;
		}

		public Criteria andPiIdGreaterThan(Integer value) {
			addCriterion("PI_ID >", value, "piId");
			return (Criteria) this;
		}

		public Criteria andPiIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("PI_ID >=", value, "piId");
			return (Criteria) this;
		}

		public Criteria andPiIdLessThan(Integer value) {
			addCriterion("PI_ID <", value, "piId");
			return (Criteria) this;
		}

		public Criteria andPiIdLessThanOrEqualTo(Integer value) {
			addCriterion("PI_ID <=", value, "piId");
			return (Criteria) this;
		}

		public Criteria andPiIdIn(List<Integer> values) {
			addCriterion("PI_ID in", values, "piId");
			return (Criteria) this;
		}

		public Criteria andPiIdNotIn(List<Integer> values) {
			addCriterion("PI_ID not in", values, "piId");
			return (Criteria) this;
		}

		public Criteria andPiIdBetween(Integer value1, Integer value2) {
			addCriterion("PI_ID between", value1, value2, "piId");
			return (Criteria) this;
		}

		public Criteria andPiIdNotBetween(Integer value1, Integer value2) {
			addCriterion("PI_ID not between", value1, value2, "piId");
			return (Criteria) this;
		}

		public Criteria andUIdIsNull() {
			addCriterion("U_ID is null");
			return (Criteria) this;
		}

		public Criteria andUIdIsNotNull() {
			addCriterion("U_ID is not null");
			return (Criteria) this;
		}

		public Criteria andUIdEqualTo(Integer value) {
			addCriterion("U_ID =", value, "uId");
			return (Criteria) this;
		}

		public Criteria andUIdNotEqualTo(Integer value) {
			addCriterion("U_ID <>", value, "uId");
			return (Criteria) this;
		}

		public Criteria andUIdGreaterThan(Integer value) {
			addCriterion("U_ID >", value, "uId");
			return (Criteria) this;
		}

		public Criteria andUIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("U_ID >=", value, "uId");
			return (Criteria) this;
		}

		public Criteria andUIdLessThan(Integer value) {
			addCriterion("U_ID <", value, "uId");
			return (Criteria) this;
		}

		public Criteria andUIdLessThanOrEqualTo(Integer value) {
			addCriterion("U_ID <=", value, "uId");
			return (Criteria) this;
		}

		public Criteria andUIdIn(List<Integer> values) {
			addCriterion("U_ID in", values, "uId");
			return (Criteria) this;
		}

		public Criteria andUIdNotIn(List<Integer> values) {
			addCriterion("U_ID not in", values, "uId");
			return (Criteria) this;
		}

		public Criteria andUIdBetween(Integer value1, Integer value2) {
			addCriterion("U_ID between", value1, value2, "uId");
			return (Criteria) this;
		}

		public Criteria andUIdNotBetween(Integer value1, Integer value2) {
			addCriterion("U_ID not between", value1, value2, "uId");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table post_view
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table post_view
     *
     * @mbg.generated do_not_delete_during_merge Sun May 06 20:50:13 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}