package com.plm.model;

import java.util.Date;

public class PostInfo {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column post_info.PI_ID
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	private Integer piId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column post_info.U_ID
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	private Integer uId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column post_info.PI_TITLE
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	private String piTitle;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column post_info.PI_CONTENT
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	private String piContent;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column post_info.HAS_ACCESSORY
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	private Integer hasAccessory;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column post_info.POST_TIME
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	private Date postTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column post_info.POST_EDIT_TIME
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	private Date postEditTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column post_info.PI_ID
	 * @return  the value of post_info.PI_ID
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public Integer getPiId() {
		return piId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column post_info.PI_ID
	 * @param piId  the value for post_info.PI_ID
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public void setPiId(Integer piId) {
		this.piId = piId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column post_info.U_ID
	 * @return  the value of post_info.U_ID
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public Integer getuId() {
		return uId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column post_info.U_ID
	 * @param uId  the value for post_info.U_ID
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public void setuId(Integer uId) {
		this.uId = uId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column post_info.PI_TITLE
	 * @return  the value of post_info.PI_TITLE
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public String getPiTitle() {
		return piTitle;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column post_info.PI_TITLE
	 * @param piTitle  the value for post_info.PI_TITLE
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public void setPiTitle(String piTitle) {
		this.piTitle = piTitle;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column post_info.PI_CONTENT
	 * @return  the value of post_info.PI_CONTENT
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public String getPiContent() {
		return piContent;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column post_info.PI_CONTENT
	 * @param piContent  the value for post_info.PI_CONTENT
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public void setPiContent(String piContent) {
		this.piContent = piContent;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column post_info.HAS_ACCESSORY
	 * @return  the value of post_info.HAS_ACCESSORY
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public Integer getHasAccessory() {
		return hasAccessory;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column post_info.HAS_ACCESSORY
	 * @param hasAccessory  the value for post_info.HAS_ACCESSORY
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public void setHasAccessory(Integer hasAccessory) {
		this.hasAccessory = hasAccessory;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column post_info.POST_TIME
	 * @return  the value of post_info.POST_TIME
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public Date getPostTime() {
		return postTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column post_info.POST_TIME
	 * @param postTime  the value for post_info.POST_TIME
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public void setPostTime(Date postTime) {
		this.postTime = postTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column post_info.POST_EDIT_TIME
	 * @return  the value of post_info.POST_EDIT_TIME
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public Date getPostEditTime() {
		return postEditTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column post_info.POST_EDIT_TIME
	 * @param postEditTime  the value for post_info.POST_EDIT_TIME
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public void setPostEditTime(Date postEditTime) {
		this.postEditTime = postEditTime;
	}
}