package com.plm.model;

import java.util.Date;

public class ProjectOtherView {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column project_other_view.PB_ID
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	private Integer pbId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column project_other_view.PB_NAME
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	private String pbName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column project_other_view.PPI_CREATE_TIME
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	private Date ppiCreateTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column project_other_view.PPI_EDIT_TIME
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	private Date ppiEditTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column project_other_view.PPI_ID
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	private Integer ppiId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column project_other_view.PPI_TYPE
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	private Integer ppiType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column project_other_view.POI_TYPE
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	private Integer poiType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column project_other_view.POI_CONTENT
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	private String poiContent;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column project_other_view.U_ID
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	private Integer uId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column project_other_view.U_TYPE
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	private Integer uType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column project_other_view.POI_O_STATUS
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	private Integer poiOStatus;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column project_other_view.PB_ID
	 * @return  the value of project_other_view.PB_ID
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public Integer getPbId() {
		return pbId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column project_other_view.PB_ID
	 * @param pbId  the value for project_other_view.PB_ID
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public void setPbId(Integer pbId) {
		this.pbId = pbId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column project_other_view.PB_NAME
	 * @return  the value of project_other_view.PB_NAME
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public String getPbName() {
		return pbName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column project_other_view.PB_NAME
	 * @param pbName  the value for project_other_view.PB_NAME
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public void setPbName(String pbName) {
		this.pbName = pbName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column project_other_view.PPI_CREATE_TIME
	 * @return  the value of project_other_view.PPI_CREATE_TIME
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public Date getPpiCreateTime() {
		return ppiCreateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column project_other_view.PPI_CREATE_TIME
	 * @param ppiCreateTime  the value for project_other_view.PPI_CREATE_TIME
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public void setPpiCreateTime(Date ppiCreateTime) {
		this.ppiCreateTime = ppiCreateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column project_other_view.PPI_EDIT_TIME
	 * @return  the value of project_other_view.PPI_EDIT_TIME
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public Date getPpiEditTime() {
		return ppiEditTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column project_other_view.PPI_EDIT_TIME
	 * @param ppiEditTime  the value for project_other_view.PPI_EDIT_TIME
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public void setPpiEditTime(Date ppiEditTime) {
		this.ppiEditTime = ppiEditTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column project_other_view.PPI_ID
	 * @return  the value of project_other_view.PPI_ID
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public Integer getPpiId() {
		return ppiId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column project_other_view.PPI_ID
	 * @param ppiId  the value for project_other_view.PPI_ID
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public void setPpiId(Integer ppiId) {
		this.ppiId = ppiId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column project_other_view.PPI_TYPE
	 * @return  the value of project_other_view.PPI_TYPE
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public Integer getPpiType() {
		return ppiType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column project_other_view.PPI_TYPE
	 * @param ppiType  the value for project_other_view.PPI_TYPE
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public void setPpiType(Integer ppiType) {
		this.ppiType = ppiType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column project_other_view.POI_TYPE
	 * @return  the value of project_other_view.POI_TYPE
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public Integer getPoiType() {
		return poiType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column project_other_view.POI_TYPE
	 * @param poiType  the value for project_other_view.POI_TYPE
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public void setPoiType(Integer poiType) {
		this.poiType = poiType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column project_other_view.POI_CONTENT
	 * @return  the value of project_other_view.POI_CONTENT
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public String getPoiContent() {
		return poiContent;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column project_other_view.POI_CONTENT
	 * @param poiContent  the value for project_other_view.POI_CONTENT
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public void setPoiContent(String poiContent) {
		this.poiContent = poiContent;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column project_other_view.U_ID
	 * @return  the value of project_other_view.U_ID
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public Integer getuId() {
		return uId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column project_other_view.U_ID
	 * @param uId  the value for project_other_view.U_ID
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public void setuId(Integer uId) {
		this.uId = uId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column project_other_view.U_TYPE
	 * @return  the value of project_other_view.U_TYPE
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public Integer getuType() {
		return uType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column project_other_view.U_TYPE
	 * @param uType  the value for project_other_view.U_TYPE
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public void setuType(Integer uType) {
		this.uType = uType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column project_other_view.POI_O_STATUS
	 * @return  the value of project_other_view.POI_O_STATUS
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public Integer getPoiOStatus() {
		return poiOStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column project_other_view.POI_O_STATUS
	 * @param poiOStatus  the value for project_other_view.POI_O_STATUS
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public void setPoiOStatus(Integer poiOStatus) {
		this.poiOStatus = poiOStatus;
	}
}