package com.plm.model;

import java.util.Date;

public class ProjectEndView {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column project_end_view.PB_ID
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	private Integer pbId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column project_end_view.PB_NAME
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	private String pbName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column project_end_view.PPI_ID
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	private Integer ppiId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column project_end_view.PPI_CREATE_TIME
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	private Date ppiCreateTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column project_end_view.PPI_EDIT_TIME
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	private Date ppiEditTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column project_end_view.PPI_TYPE
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	private Integer ppiType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column project_end_view.PEI_MISSION
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	private String peiMission;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column project_end_view.PEI_OPOINION
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	private String peiOpoinion;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column project_end_view.PEI_LEVEL
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	private Integer peiLevel;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column project_end_view.PMI_CONTENT
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	private String pmiContent;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column project_end_view.PB_TYPE
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	private Integer pbType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column project_end_view.PB_LEVEL
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	private Integer pbLevel;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column project_end_view.SUBJECT_TYPE
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	private Integer subjectType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column project_end_view.U_ID
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	private Integer uId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column project_end_view.U_TYPE
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	private Integer uType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column project_end_view.WS_STATUS
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	private Integer wsStatus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column project_end_view.F_STATUS
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	private Integer fStatus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column project_end_view.PEI_O_STATUS
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	private Integer peiOStatus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column project_end_view.PMI_O_STATUS
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	private Integer pmiOStatus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column project_end_view.PSI_O_STATUS
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	private Integer psiOStatus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column project_end_view.PB_STATUS
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	private Integer pbStatus;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column project_end_view.PB_ID
	 * @return  the value of project_end_view.PB_ID
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public Integer getPbId() {
		return pbId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column project_end_view.PB_ID
	 * @param pbId  the value for project_end_view.PB_ID
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public void setPbId(Integer pbId) {
		this.pbId = pbId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column project_end_view.PB_NAME
	 * @return  the value of project_end_view.PB_NAME
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public String getPbName() {
		return pbName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column project_end_view.PB_NAME
	 * @param pbName  the value for project_end_view.PB_NAME
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public void setPbName(String pbName) {
		this.pbName = pbName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column project_end_view.PPI_ID
	 * @return  the value of project_end_view.PPI_ID
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public Integer getPpiId() {
		return ppiId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column project_end_view.PPI_ID
	 * @param ppiId  the value for project_end_view.PPI_ID
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public void setPpiId(Integer ppiId) {
		this.ppiId = ppiId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column project_end_view.PPI_CREATE_TIME
	 * @return  the value of project_end_view.PPI_CREATE_TIME
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public Date getPpiCreateTime() {
		return ppiCreateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column project_end_view.PPI_CREATE_TIME
	 * @param ppiCreateTime  the value for project_end_view.PPI_CREATE_TIME
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public void setPpiCreateTime(Date ppiCreateTime) {
		this.ppiCreateTime = ppiCreateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column project_end_view.PPI_EDIT_TIME
	 * @return  the value of project_end_view.PPI_EDIT_TIME
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public Date getPpiEditTime() {
		return ppiEditTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column project_end_view.PPI_EDIT_TIME
	 * @param ppiEditTime  the value for project_end_view.PPI_EDIT_TIME
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public void setPpiEditTime(Date ppiEditTime) {
		this.ppiEditTime = ppiEditTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column project_end_view.PPI_TYPE
	 * @return  the value of project_end_view.PPI_TYPE
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public Integer getPpiType() {
		return ppiType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column project_end_view.PPI_TYPE
	 * @param ppiType  the value for project_end_view.PPI_TYPE
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public void setPpiType(Integer ppiType) {
		this.ppiType = ppiType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column project_end_view.PEI_MISSION
	 * @return  the value of project_end_view.PEI_MISSION
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public String getPeiMission() {
		return peiMission;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column project_end_view.PEI_MISSION
	 * @param peiMission  the value for project_end_view.PEI_MISSION
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public void setPeiMission(String peiMission) {
		this.peiMission = peiMission;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column project_end_view.PEI_OPOINION
	 * @return  the value of project_end_view.PEI_OPOINION
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public String getPeiOpoinion() {
		return peiOpoinion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column project_end_view.PEI_OPOINION
	 * @param peiOpoinion  the value for project_end_view.PEI_OPOINION
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public void setPeiOpoinion(String peiOpoinion) {
		this.peiOpoinion = peiOpoinion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column project_end_view.PEI_LEVEL
	 * @return  the value of project_end_view.PEI_LEVEL
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public Integer getPeiLevel() {
		return peiLevel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column project_end_view.PEI_LEVEL
	 * @param peiLevel  the value for project_end_view.PEI_LEVEL
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public void setPeiLevel(Integer peiLevel) {
		this.peiLevel = peiLevel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column project_end_view.PMI_CONTENT
	 * @return  the value of project_end_view.PMI_CONTENT
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public String getPmiContent() {
		return pmiContent;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column project_end_view.PMI_CONTENT
	 * @param pmiContent  the value for project_end_view.PMI_CONTENT
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public void setPmiContent(String pmiContent) {
		this.pmiContent = pmiContent;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column project_end_view.PB_TYPE
	 * @return  the value of project_end_view.PB_TYPE
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public Integer getPbType() {
		return pbType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column project_end_view.PB_TYPE
	 * @param pbType  the value for project_end_view.PB_TYPE
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public void setPbType(Integer pbType) {
		this.pbType = pbType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column project_end_view.PB_LEVEL
	 * @return  the value of project_end_view.PB_LEVEL
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public Integer getPbLevel() {
		return pbLevel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column project_end_view.PB_LEVEL
	 * @param pbLevel  the value for project_end_view.PB_LEVEL
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public void setPbLevel(Integer pbLevel) {
		this.pbLevel = pbLevel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column project_end_view.SUBJECT_TYPE
	 * @return  the value of project_end_view.SUBJECT_TYPE
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public Integer getSubjectType() {
		return subjectType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column project_end_view.SUBJECT_TYPE
	 * @param subjectType  the value for project_end_view.SUBJECT_TYPE
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public void setSubjectType(Integer subjectType) {
		this.subjectType = subjectType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column project_end_view.U_ID
	 * @return  the value of project_end_view.U_ID
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public Integer getuId() {
		return uId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column project_end_view.U_ID
	 * @param uId  the value for project_end_view.U_ID
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public void setuId(Integer uId) {
		this.uId = uId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column project_end_view.U_TYPE
	 * @return  the value of project_end_view.U_TYPE
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public Integer getuType() {
		return uType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column project_end_view.U_TYPE
	 * @param uType  the value for project_end_view.U_TYPE
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public void setuType(Integer uType) {
		this.uType = uType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column project_end_view.WS_STATUS
	 * @return  the value of project_end_view.WS_STATUS
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public Integer getWsStatus() {
		return wsStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column project_end_view.WS_STATUS
	 * @param wsStatus  the value for project_end_view.WS_STATUS
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public void setWsStatus(Integer wsStatus) {
		this.wsStatus = wsStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column project_end_view.F_STATUS
	 * @return  the value of project_end_view.F_STATUS
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public Integer getfStatus() {
		return fStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column project_end_view.F_STATUS
	 * @param fStatus  the value for project_end_view.F_STATUS
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public void setfStatus(Integer fStatus) {
		this.fStatus = fStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column project_end_view.PEI_O_STATUS
	 * @return  the value of project_end_view.PEI_O_STATUS
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public Integer getPeiOStatus() {
		return peiOStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column project_end_view.PEI_O_STATUS
	 * @param peiOStatus  the value for project_end_view.PEI_O_STATUS
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public void setPeiOStatus(Integer peiOStatus) {
		this.peiOStatus = peiOStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column project_end_view.PMI_O_STATUS
	 * @return  the value of project_end_view.PMI_O_STATUS
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public Integer getPmiOStatus() {
		return pmiOStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column project_end_view.PMI_O_STATUS
	 * @param pmiOStatus  the value for project_end_view.PMI_O_STATUS
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public void setPmiOStatus(Integer pmiOStatus) {
		this.pmiOStatus = pmiOStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column project_end_view.PSI_O_STATUS
	 * @return  the value of project_end_view.PSI_O_STATUS
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public Integer getPsiOStatus() {
		return psiOStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column project_end_view.PSI_O_STATUS
	 * @param psiOStatus  the value for project_end_view.PSI_O_STATUS
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public void setPsiOStatus(Integer psiOStatus) {
		this.psiOStatus = psiOStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column project_end_view.PB_STATUS
	 * @return  the value of project_end_view.PB_STATUS
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public Integer getPbStatus() {
		return pbStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column project_end_view.PB_STATUS
	 * @param pbStatus  the value for project_end_view.PB_STATUS
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public void setPbStatus(Integer pbStatus) {
		this.pbStatus = pbStatus;
	}
}