package com.plm.model;

import java.util.Date;

public class ProjectBase {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column project_base.PB_ID
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	private Integer pbId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column project_base.PP_ID
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	private Integer ppId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column project_base.PB_CREATE_TIME
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	private Date pbCreateTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column project_base.PB_EDIT_TIME
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	private Date pbEditTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column project_base.PB_NAME
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	private String pbName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column project_base.PB_LEVEL
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	private Integer pbLevel;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column project_base.PB_TYPE
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	private Integer pbType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column project_base.SUBJECT_TYPE
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	private Integer subjectType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column project_base.PSI_BRIEF
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	private String psiBrief;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column project_base.PSI_REASON
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	private String psiReason;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column project_base.PSI_CONTENT
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	private String psiContent;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column project_base.PSI_FEATURE
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	private String psiFeature;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column project_base.PSI_PLAN
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	private String psiPlan;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column project_base.PSI_RESULT
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	private String psiResult;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column project_base.F_CONTENT
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	private String fContent;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column project_base.F_OPINION
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	private String fOpinion;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column project_base.F_OPINION_TIME
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	private Date fOpinionTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column project_base.PB_STATUS
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	private Integer pbStatus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column project_base.PSI_O_STATUS
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	private Integer psiOStatus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column project_base.PMI_TIME
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	private Date pmiTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column project_base.PMI_O_STATUS
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	private Integer pmiOStatus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column project_base.PEI_TIME
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	private Date peiTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column project_base.PEI_O_STATUS
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	private Integer peiOStatus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column project_base.POI_TIME
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	private Date poiTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column project_base.POI_O_STATUS
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	private Integer poiOStatus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column project_base.F_STATUS
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	private Integer fStatus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column project_base.WS_STATUS
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	private Integer wsStatus;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column project_base.PB_ID
	 * @return  the value of project_base.PB_ID
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public Integer getPbId() {
		return pbId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column project_base.PB_ID
	 * @param pbId  the value for project_base.PB_ID
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public void setPbId(Integer pbId) {
		this.pbId = pbId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column project_base.PP_ID
	 * @return  the value of project_base.PP_ID
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public Integer getPpId() {
		return ppId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column project_base.PP_ID
	 * @param ppId  the value for project_base.PP_ID
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public void setPpId(Integer ppId) {
		this.ppId = ppId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column project_base.PB_CREATE_TIME
	 * @return  the value of project_base.PB_CREATE_TIME
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public Date getPbCreateTime() {
		return pbCreateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column project_base.PB_CREATE_TIME
	 * @param pbCreateTime  the value for project_base.PB_CREATE_TIME
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public void setPbCreateTime(Date pbCreateTime) {
		this.pbCreateTime = pbCreateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column project_base.PB_EDIT_TIME
	 * @return  the value of project_base.PB_EDIT_TIME
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public Date getPbEditTime() {
		return pbEditTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column project_base.PB_EDIT_TIME
	 * @param pbEditTime  the value for project_base.PB_EDIT_TIME
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public void setPbEditTime(Date pbEditTime) {
		this.pbEditTime = pbEditTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column project_base.PB_NAME
	 * @return  the value of project_base.PB_NAME
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public String getPbName() {
		return pbName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column project_base.PB_NAME
	 * @param pbName  the value for project_base.PB_NAME
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public void setPbName(String pbName) {
		this.pbName = pbName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column project_base.PB_LEVEL
	 * @return  the value of project_base.PB_LEVEL
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public Integer getPbLevel() {
		return pbLevel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column project_base.PB_LEVEL
	 * @param pbLevel  the value for project_base.PB_LEVEL
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public void setPbLevel(Integer pbLevel) {
		this.pbLevel = pbLevel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column project_base.PB_TYPE
	 * @return  the value of project_base.PB_TYPE
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public Integer getPbType() {
		return pbType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column project_base.PB_TYPE
	 * @param pbType  the value for project_base.PB_TYPE
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public void setPbType(Integer pbType) {
		this.pbType = pbType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column project_base.SUBJECT_TYPE
	 * @return  the value of project_base.SUBJECT_TYPE
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public Integer getSubjectType() {
		return subjectType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column project_base.SUBJECT_TYPE
	 * @param subjectType  the value for project_base.SUBJECT_TYPE
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public void setSubjectType(Integer subjectType) {
		this.subjectType = subjectType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column project_base.PSI_BRIEF
	 * @return  the value of project_base.PSI_BRIEF
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public String getPsiBrief() {
		return psiBrief;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column project_base.PSI_BRIEF
	 * @param psiBrief  the value for project_base.PSI_BRIEF
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public void setPsiBrief(String psiBrief) {
		this.psiBrief = psiBrief;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column project_base.PSI_REASON
	 * @return  the value of project_base.PSI_REASON
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public String getPsiReason() {
		return psiReason;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column project_base.PSI_REASON
	 * @param psiReason  the value for project_base.PSI_REASON
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public void setPsiReason(String psiReason) {
		this.psiReason = psiReason;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column project_base.PSI_CONTENT
	 * @return  the value of project_base.PSI_CONTENT
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public String getPsiContent() {
		return psiContent;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column project_base.PSI_CONTENT
	 * @param psiContent  the value for project_base.PSI_CONTENT
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public void setPsiContent(String psiContent) {
		this.psiContent = psiContent;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column project_base.PSI_FEATURE
	 * @return  the value of project_base.PSI_FEATURE
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public String getPsiFeature() {
		return psiFeature;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column project_base.PSI_FEATURE
	 * @param psiFeature  the value for project_base.PSI_FEATURE
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public void setPsiFeature(String psiFeature) {
		this.psiFeature = psiFeature;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column project_base.PSI_PLAN
	 * @return  the value of project_base.PSI_PLAN
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public String getPsiPlan() {
		return psiPlan;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column project_base.PSI_PLAN
	 * @param psiPlan  the value for project_base.PSI_PLAN
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public void setPsiPlan(String psiPlan) {
		this.psiPlan = psiPlan;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column project_base.PSI_RESULT
	 * @return  the value of project_base.PSI_RESULT
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public String getPsiResult() {
		return psiResult;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column project_base.PSI_RESULT
	 * @param psiResult  the value for project_base.PSI_RESULT
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public void setPsiResult(String psiResult) {
		this.psiResult = psiResult;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column project_base.F_CONTENT
	 * @return  the value of project_base.F_CONTENT
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public String getfContent() {
		return fContent;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column project_base.F_CONTENT
	 * @param fContent  the value for project_base.F_CONTENT
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public void setfContent(String fContent) {
		this.fContent = fContent;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column project_base.F_OPINION
	 * @return  the value of project_base.F_OPINION
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public String getfOpinion() {
		return fOpinion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column project_base.F_OPINION
	 * @param fOpinion  the value for project_base.F_OPINION
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public void setfOpinion(String fOpinion) {
		this.fOpinion = fOpinion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column project_base.F_OPINION_TIME
	 * @return  the value of project_base.F_OPINION_TIME
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public Date getfOpinionTime() {
		return fOpinionTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column project_base.F_OPINION_TIME
	 * @param fOpinionTime  the value for project_base.F_OPINION_TIME
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public void setfOpinionTime(Date fOpinionTime) {
		this.fOpinionTime = fOpinionTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column project_base.PB_STATUS
	 * @return  the value of project_base.PB_STATUS
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public Integer getPbStatus() {
		return pbStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column project_base.PB_STATUS
	 * @param pbStatus  the value for project_base.PB_STATUS
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public void setPbStatus(Integer pbStatus) {
		this.pbStatus = pbStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column project_base.PSI_O_STATUS
	 * @return  the value of project_base.PSI_O_STATUS
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public Integer getPsiOStatus() {
		return psiOStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column project_base.PSI_O_STATUS
	 * @param psiOStatus  the value for project_base.PSI_O_STATUS
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public void setPsiOStatus(Integer psiOStatus) {
		this.psiOStatus = psiOStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column project_base.PMI_TIME
	 * @return  the value of project_base.PMI_TIME
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public Date getPmiTime() {
		return pmiTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column project_base.PMI_TIME
	 * @param pmiTime  the value for project_base.PMI_TIME
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public void setPmiTime(Date pmiTime) {
		this.pmiTime = pmiTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column project_base.PMI_O_STATUS
	 * @return  the value of project_base.PMI_O_STATUS
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public Integer getPmiOStatus() {
		return pmiOStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column project_base.PMI_O_STATUS
	 * @param pmiOStatus  the value for project_base.PMI_O_STATUS
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public void setPmiOStatus(Integer pmiOStatus) {
		this.pmiOStatus = pmiOStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column project_base.PEI_TIME
	 * @return  the value of project_base.PEI_TIME
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public Date getPeiTime() {
		return peiTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column project_base.PEI_TIME
	 * @param peiTime  the value for project_base.PEI_TIME
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public void setPeiTime(Date peiTime) {
		this.peiTime = peiTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column project_base.PEI_O_STATUS
	 * @return  the value of project_base.PEI_O_STATUS
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public Integer getPeiOStatus() {
		return peiOStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column project_base.PEI_O_STATUS
	 * @param peiOStatus  the value for project_base.PEI_O_STATUS
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public void setPeiOStatus(Integer peiOStatus) {
		this.peiOStatus = peiOStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column project_base.POI_TIME
	 * @return  the value of project_base.POI_TIME
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public Date getPoiTime() {
		return poiTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column project_base.POI_TIME
	 * @param poiTime  the value for project_base.POI_TIME
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public void setPoiTime(Date poiTime) {
		this.poiTime = poiTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column project_base.POI_O_STATUS
	 * @return  the value of project_base.POI_O_STATUS
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public Integer getPoiOStatus() {
		return poiOStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column project_base.POI_O_STATUS
	 * @param poiOStatus  the value for project_base.POI_O_STATUS
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public void setPoiOStatus(Integer poiOStatus) {
		this.poiOStatus = poiOStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column project_base.F_STATUS
	 * @return  the value of project_base.F_STATUS
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public Integer getfStatus() {
		return fStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column project_base.F_STATUS
	 * @param fStatus  the value for project_base.F_STATUS
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public void setfStatus(Integer fStatus) {
		this.fStatus = fStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column project_base.WS_STATUS
	 * @return  the value of project_base.WS_STATUS
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public Integer getWsStatus() {
		return wsStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column project_base.WS_STATUS
	 * @param wsStatus  the value for project_base.WS_STATUS
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public void setWsStatus(Integer wsStatus) {
		this.wsStatus = wsStatus;
	}
}