package com.plm.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ProjectStartViewExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table project_start_view
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table project_start_view
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table project_start_view
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table project_start_view
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public ProjectStartViewExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table project_start_view
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table project_start_view
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table project_start_view
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table project_start_view
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table project_start_view
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table project_start_view
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table project_start_view
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table project_start_view
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table project_start_view
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table project_start_view
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table project_start_view
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andPbIdIsNull() {
			addCriterion("PB_ID is null");
			return (Criteria) this;
		}

		public Criteria andPbIdIsNotNull() {
			addCriterion("PB_ID is not null");
			return (Criteria) this;
		}

		public Criteria andPbIdEqualTo(Integer value) {
			addCriterion("PB_ID =", value, "pbId");
			return (Criteria) this;
		}

		public Criteria andPbIdNotEqualTo(Integer value) {
			addCriterion("PB_ID <>", value, "pbId");
			return (Criteria) this;
		}

		public Criteria andPbIdGreaterThan(Integer value) {
			addCriterion("PB_ID >", value, "pbId");
			return (Criteria) this;
		}

		public Criteria andPbIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("PB_ID >=", value, "pbId");
			return (Criteria) this;
		}

		public Criteria andPbIdLessThan(Integer value) {
			addCriterion("PB_ID <", value, "pbId");
			return (Criteria) this;
		}

		public Criteria andPbIdLessThanOrEqualTo(Integer value) {
			addCriterion("PB_ID <=", value, "pbId");
			return (Criteria) this;
		}

		public Criteria andPbIdIn(List<Integer> values) {
			addCriterion("PB_ID in", values, "pbId");
			return (Criteria) this;
		}

		public Criteria andPbIdNotIn(List<Integer> values) {
			addCriterion("PB_ID not in", values, "pbId");
			return (Criteria) this;
		}

		public Criteria andPbIdBetween(Integer value1, Integer value2) {
			addCriterion("PB_ID between", value1, value2, "pbId");
			return (Criteria) this;
		}

		public Criteria andPbIdNotBetween(Integer value1, Integer value2) {
			addCriterion("PB_ID not between", value1, value2, "pbId");
			return (Criteria) this;
		}

		public Criteria andPpiIdIsNull() {
			addCriterion("PPI_ID is null");
			return (Criteria) this;
		}

		public Criteria andPpiIdIsNotNull() {
			addCriterion("PPI_ID is not null");
			return (Criteria) this;
		}

		public Criteria andPpiIdEqualTo(Integer value) {
			addCriterion("PPI_ID =", value, "ppiId");
			return (Criteria) this;
		}

		public Criteria andPpiIdNotEqualTo(Integer value) {
			addCriterion("PPI_ID <>", value, "ppiId");
			return (Criteria) this;
		}

		public Criteria andPpiIdGreaterThan(Integer value) {
			addCriterion("PPI_ID >", value, "ppiId");
			return (Criteria) this;
		}

		public Criteria andPpiIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("PPI_ID >=", value, "ppiId");
			return (Criteria) this;
		}

		public Criteria andPpiIdLessThan(Integer value) {
			addCriterion("PPI_ID <", value, "ppiId");
			return (Criteria) this;
		}

		public Criteria andPpiIdLessThanOrEqualTo(Integer value) {
			addCriterion("PPI_ID <=", value, "ppiId");
			return (Criteria) this;
		}

		public Criteria andPpiIdIn(List<Integer> values) {
			addCriterion("PPI_ID in", values, "ppiId");
			return (Criteria) this;
		}

		public Criteria andPpiIdNotIn(List<Integer> values) {
			addCriterion("PPI_ID not in", values, "ppiId");
			return (Criteria) this;
		}

		public Criteria andPpiIdBetween(Integer value1, Integer value2) {
			addCriterion("PPI_ID between", value1, value2, "ppiId");
			return (Criteria) this;
		}

		public Criteria andPpiIdNotBetween(Integer value1, Integer value2) {
			addCriterion("PPI_ID not between", value1, value2, "ppiId");
			return (Criteria) this;
		}

		public Criteria andPpiCreateTimeIsNull() {
			addCriterion("PPI_CREATE_TIME is null");
			return (Criteria) this;
		}

		public Criteria andPpiCreateTimeIsNotNull() {
			addCriterion("PPI_CREATE_TIME is not null");
			return (Criteria) this;
		}

		public Criteria andPpiCreateTimeEqualTo(Date value) {
			addCriterion("PPI_CREATE_TIME =", value, "ppiCreateTime");
			return (Criteria) this;
		}

		public Criteria andPpiCreateTimeNotEqualTo(Date value) {
			addCriterion("PPI_CREATE_TIME <>", value, "ppiCreateTime");
			return (Criteria) this;
		}

		public Criteria andPpiCreateTimeGreaterThan(Date value) {
			addCriterion("PPI_CREATE_TIME >", value, "ppiCreateTime");
			return (Criteria) this;
		}

		public Criteria andPpiCreateTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("PPI_CREATE_TIME >=", value, "ppiCreateTime");
			return (Criteria) this;
		}

		public Criteria andPpiCreateTimeLessThan(Date value) {
			addCriterion("PPI_CREATE_TIME <", value, "ppiCreateTime");
			return (Criteria) this;
		}

		public Criteria andPpiCreateTimeLessThanOrEqualTo(Date value) {
			addCriterion("PPI_CREATE_TIME <=", value, "ppiCreateTime");
			return (Criteria) this;
		}

		public Criteria andPpiCreateTimeIn(List<Date> values) {
			addCriterion("PPI_CREATE_TIME in", values, "ppiCreateTime");
			return (Criteria) this;
		}

		public Criteria andPpiCreateTimeNotIn(List<Date> values) {
			addCriterion("PPI_CREATE_TIME not in", values, "ppiCreateTime");
			return (Criteria) this;
		}

		public Criteria andPpiCreateTimeBetween(Date value1, Date value2) {
			addCriterion("PPI_CREATE_TIME between", value1, value2, "ppiCreateTime");
			return (Criteria) this;
		}

		public Criteria andPpiCreateTimeNotBetween(Date value1, Date value2) {
			addCriterion("PPI_CREATE_TIME not between", value1, value2, "ppiCreateTime");
			return (Criteria) this;
		}

		public Criteria andPpiEditTimeIsNull() {
			addCriterion("PPI_EDIT_TIME is null");
			return (Criteria) this;
		}

		public Criteria andPpiEditTimeIsNotNull() {
			addCriterion("PPI_EDIT_TIME is not null");
			return (Criteria) this;
		}

		public Criteria andPpiEditTimeEqualTo(Date value) {
			addCriterion("PPI_EDIT_TIME =", value, "ppiEditTime");
			return (Criteria) this;
		}

		public Criteria andPpiEditTimeNotEqualTo(Date value) {
			addCriterion("PPI_EDIT_TIME <>", value, "ppiEditTime");
			return (Criteria) this;
		}

		public Criteria andPpiEditTimeGreaterThan(Date value) {
			addCriterion("PPI_EDIT_TIME >", value, "ppiEditTime");
			return (Criteria) this;
		}

		public Criteria andPpiEditTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("PPI_EDIT_TIME >=", value, "ppiEditTime");
			return (Criteria) this;
		}

		public Criteria andPpiEditTimeLessThan(Date value) {
			addCriterion("PPI_EDIT_TIME <", value, "ppiEditTime");
			return (Criteria) this;
		}

		public Criteria andPpiEditTimeLessThanOrEqualTo(Date value) {
			addCriterion("PPI_EDIT_TIME <=", value, "ppiEditTime");
			return (Criteria) this;
		}

		public Criteria andPpiEditTimeIn(List<Date> values) {
			addCriterion("PPI_EDIT_TIME in", values, "ppiEditTime");
			return (Criteria) this;
		}

		public Criteria andPpiEditTimeNotIn(List<Date> values) {
			addCriterion("PPI_EDIT_TIME not in", values, "ppiEditTime");
			return (Criteria) this;
		}

		public Criteria andPpiEditTimeBetween(Date value1, Date value2) {
			addCriterion("PPI_EDIT_TIME between", value1, value2, "ppiEditTime");
			return (Criteria) this;
		}

		public Criteria andPpiEditTimeNotBetween(Date value1, Date value2) {
			addCriterion("PPI_EDIT_TIME not between", value1, value2, "ppiEditTime");
			return (Criteria) this;
		}

		public Criteria andPpiTypeIsNull() {
			addCriterion("PPI_TYPE is null");
			return (Criteria) this;
		}

		public Criteria andPpiTypeIsNotNull() {
			addCriterion("PPI_TYPE is not null");
			return (Criteria) this;
		}

		public Criteria andPpiTypeEqualTo(Integer value) {
			addCriterion("PPI_TYPE =", value, "ppiType");
			return (Criteria) this;
		}

		public Criteria andPpiTypeNotEqualTo(Integer value) {
			addCriterion("PPI_TYPE <>", value, "ppiType");
			return (Criteria) this;
		}

		public Criteria andPpiTypeGreaterThan(Integer value) {
			addCriterion("PPI_TYPE >", value, "ppiType");
			return (Criteria) this;
		}

		public Criteria andPpiTypeGreaterThanOrEqualTo(Integer value) {
			addCriterion("PPI_TYPE >=", value, "ppiType");
			return (Criteria) this;
		}

		public Criteria andPpiTypeLessThan(Integer value) {
			addCriterion("PPI_TYPE <", value, "ppiType");
			return (Criteria) this;
		}

		public Criteria andPpiTypeLessThanOrEqualTo(Integer value) {
			addCriterion("PPI_TYPE <=", value, "ppiType");
			return (Criteria) this;
		}

		public Criteria andPpiTypeIn(List<Integer> values) {
			addCriterion("PPI_TYPE in", values, "ppiType");
			return (Criteria) this;
		}

		public Criteria andPpiTypeNotIn(List<Integer> values) {
			addCriterion("PPI_TYPE not in", values, "ppiType");
			return (Criteria) this;
		}

		public Criteria andPpiTypeBetween(Integer value1, Integer value2) {
			addCriterion("PPI_TYPE between", value1, value2, "ppiType");
			return (Criteria) this;
		}

		public Criteria andPpiTypeNotBetween(Integer value1, Integer value2) {
			addCriterion("PPI_TYPE not between", value1, value2, "ppiType");
			return (Criteria) this;
		}

		public Criteria andPbCreateTimeIsNull() {
			addCriterion("PB_CREATE_TIME is null");
			return (Criteria) this;
		}

		public Criteria andPbCreateTimeIsNotNull() {
			addCriterion("PB_CREATE_TIME is not null");
			return (Criteria) this;
		}

		public Criteria andPbCreateTimeEqualTo(Date value) {
			addCriterion("PB_CREATE_TIME =", value, "pbCreateTime");
			return (Criteria) this;
		}

		public Criteria andPbCreateTimeNotEqualTo(Date value) {
			addCriterion("PB_CREATE_TIME <>", value, "pbCreateTime");
			return (Criteria) this;
		}

		public Criteria andPbCreateTimeGreaterThan(Date value) {
			addCriterion("PB_CREATE_TIME >", value, "pbCreateTime");
			return (Criteria) this;
		}

		public Criteria andPbCreateTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("PB_CREATE_TIME >=", value, "pbCreateTime");
			return (Criteria) this;
		}

		public Criteria andPbCreateTimeLessThan(Date value) {
			addCriterion("PB_CREATE_TIME <", value, "pbCreateTime");
			return (Criteria) this;
		}

		public Criteria andPbCreateTimeLessThanOrEqualTo(Date value) {
			addCriterion("PB_CREATE_TIME <=", value, "pbCreateTime");
			return (Criteria) this;
		}

		public Criteria andPbCreateTimeIn(List<Date> values) {
			addCriterion("PB_CREATE_TIME in", values, "pbCreateTime");
			return (Criteria) this;
		}

		public Criteria andPbCreateTimeNotIn(List<Date> values) {
			addCriterion("PB_CREATE_TIME not in", values, "pbCreateTime");
			return (Criteria) this;
		}

		public Criteria andPbCreateTimeBetween(Date value1, Date value2) {
			addCriterion("PB_CREATE_TIME between", value1, value2, "pbCreateTime");
			return (Criteria) this;
		}

		public Criteria andPbCreateTimeNotBetween(Date value1, Date value2) {
			addCriterion("PB_CREATE_TIME not between", value1, value2, "pbCreateTime");
			return (Criteria) this;
		}

		public Criteria andPbEditTimeIsNull() {
			addCriterion("PB_EDIT_TIME is null");
			return (Criteria) this;
		}

		public Criteria andPbEditTimeIsNotNull() {
			addCriterion("PB_EDIT_TIME is not null");
			return (Criteria) this;
		}

		public Criteria andPbEditTimeEqualTo(Date value) {
			addCriterion("PB_EDIT_TIME =", value, "pbEditTime");
			return (Criteria) this;
		}

		public Criteria andPbEditTimeNotEqualTo(Date value) {
			addCriterion("PB_EDIT_TIME <>", value, "pbEditTime");
			return (Criteria) this;
		}

		public Criteria andPbEditTimeGreaterThan(Date value) {
			addCriterion("PB_EDIT_TIME >", value, "pbEditTime");
			return (Criteria) this;
		}

		public Criteria andPbEditTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("PB_EDIT_TIME >=", value, "pbEditTime");
			return (Criteria) this;
		}

		public Criteria andPbEditTimeLessThan(Date value) {
			addCriterion("PB_EDIT_TIME <", value, "pbEditTime");
			return (Criteria) this;
		}

		public Criteria andPbEditTimeLessThanOrEqualTo(Date value) {
			addCriterion("PB_EDIT_TIME <=", value, "pbEditTime");
			return (Criteria) this;
		}

		public Criteria andPbEditTimeIn(List<Date> values) {
			addCriterion("PB_EDIT_TIME in", values, "pbEditTime");
			return (Criteria) this;
		}

		public Criteria andPbEditTimeNotIn(List<Date> values) {
			addCriterion("PB_EDIT_TIME not in", values, "pbEditTime");
			return (Criteria) this;
		}

		public Criteria andPbEditTimeBetween(Date value1, Date value2) {
			addCriterion("PB_EDIT_TIME between", value1, value2, "pbEditTime");
			return (Criteria) this;
		}

		public Criteria andPbEditTimeNotBetween(Date value1, Date value2) {
			addCriterion("PB_EDIT_TIME not between", value1, value2, "pbEditTime");
			return (Criteria) this;
		}

		public Criteria andPbNameIsNull() {
			addCriterion("PB_NAME is null");
			return (Criteria) this;
		}

		public Criteria andPbNameIsNotNull() {
			addCriterion("PB_NAME is not null");
			return (Criteria) this;
		}

		public Criteria andPbNameEqualTo(String value) {
			addCriterion("PB_NAME =", value, "pbName");
			return (Criteria) this;
		}

		public Criteria andPbNameNotEqualTo(String value) {
			addCriterion("PB_NAME <>", value, "pbName");
			return (Criteria) this;
		}

		public Criteria andPbNameGreaterThan(String value) {
			addCriterion("PB_NAME >", value, "pbName");
			return (Criteria) this;
		}

		public Criteria andPbNameGreaterThanOrEqualTo(String value) {
			addCriterion("PB_NAME >=", value, "pbName");
			return (Criteria) this;
		}

		public Criteria andPbNameLessThan(String value) {
			addCriterion("PB_NAME <", value, "pbName");
			return (Criteria) this;
		}

		public Criteria andPbNameLessThanOrEqualTo(String value) {
			addCriterion("PB_NAME <=", value, "pbName");
			return (Criteria) this;
		}

		public Criteria andPbNameLike(String value) {
			addCriterion("PB_NAME like", value, "pbName");
			return (Criteria) this;
		}

		public Criteria andPbNameNotLike(String value) {
			addCriterion("PB_NAME not like", value, "pbName");
			return (Criteria) this;
		}

		public Criteria andPbNameIn(List<String> values) {
			addCriterion("PB_NAME in", values, "pbName");
			return (Criteria) this;
		}

		public Criteria andPbNameNotIn(List<String> values) {
			addCriterion("PB_NAME not in", values, "pbName");
			return (Criteria) this;
		}

		public Criteria andPbNameBetween(String value1, String value2) {
			addCriterion("PB_NAME between", value1, value2, "pbName");
			return (Criteria) this;
		}

		public Criteria andPbNameNotBetween(String value1, String value2) {
			addCriterion("PB_NAME not between", value1, value2, "pbName");
			return (Criteria) this;
		}

		public Criteria andPbLevelIsNull() {
			addCriterion("PB_LEVEL is null");
			return (Criteria) this;
		}

		public Criteria andPbLevelIsNotNull() {
			addCriterion("PB_LEVEL is not null");
			return (Criteria) this;
		}

		public Criteria andPbLevelEqualTo(Integer value) {
			addCriterion("PB_LEVEL =", value, "pbLevel");
			return (Criteria) this;
		}

		public Criteria andPbLevelNotEqualTo(Integer value) {
			addCriterion("PB_LEVEL <>", value, "pbLevel");
			return (Criteria) this;
		}

		public Criteria andPbLevelGreaterThan(Integer value) {
			addCriterion("PB_LEVEL >", value, "pbLevel");
			return (Criteria) this;
		}

		public Criteria andPbLevelGreaterThanOrEqualTo(Integer value) {
			addCriterion("PB_LEVEL >=", value, "pbLevel");
			return (Criteria) this;
		}

		public Criteria andPbLevelLessThan(Integer value) {
			addCriterion("PB_LEVEL <", value, "pbLevel");
			return (Criteria) this;
		}

		public Criteria andPbLevelLessThanOrEqualTo(Integer value) {
			addCriterion("PB_LEVEL <=", value, "pbLevel");
			return (Criteria) this;
		}

		public Criteria andPbLevelIn(List<Integer> values) {
			addCriterion("PB_LEVEL in", values, "pbLevel");
			return (Criteria) this;
		}

		public Criteria andPbLevelNotIn(List<Integer> values) {
			addCriterion("PB_LEVEL not in", values, "pbLevel");
			return (Criteria) this;
		}

		public Criteria andPbLevelBetween(Integer value1, Integer value2) {
			addCriterion("PB_LEVEL between", value1, value2, "pbLevel");
			return (Criteria) this;
		}

		public Criteria andPbLevelNotBetween(Integer value1, Integer value2) {
			addCriterion("PB_LEVEL not between", value1, value2, "pbLevel");
			return (Criteria) this;
		}

		public Criteria andPbTypeIsNull() {
			addCriterion("PB_TYPE is null");
			return (Criteria) this;
		}

		public Criteria andPbTypeIsNotNull() {
			addCriterion("PB_TYPE is not null");
			return (Criteria) this;
		}

		public Criteria andPbTypeEqualTo(Integer value) {
			addCriterion("PB_TYPE =", value, "pbType");
			return (Criteria) this;
		}

		public Criteria andPbTypeNotEqualTo(Integer value) {
			addCriterion("PB_TYPE <>", value, "pbType");
			return (Criteria) this;
		}

		public Criteria andPbTypeGreaterThan(Integer value) {
			addCriterion("PB_TYPE >", value, "pbType");
			return (Criteria) this;
		}

		public Criteria andPbTypeGreaterThanOrEqualTo(Integer value) {
			addCriterion("PB_TYPE >=", value, "pbType");
			return (Criteria) this;
		}

		public Criteria andPbTypeLessThan(Integer value) {
			addCriterion("PB_TYPE <", value, "pbType");
			return (Criteria) this;
		}

		public Criteria andPbTypeLessThanOrEqualTo(Integer value) {
			addCriterion("PB_TYPE <=", value, "pbType");
			return (Criteria) this;
		}

		public Criteria andPbTypeIn(List<Integer> values) {
			addCriterion("PB_TYPE in", values, "pbType");
			return (Criteria) this;
		}

		public Criteria andPbTypeNotIn(List<Integer> values) {
			addCriterion("PB_TYPE not in", values, "pbType");
			return (Criteria) this;
		}

		public Criteria andPbTypeBetween(Integer value1, Integer value2) {
			addCriterion("PB_TYPE between", value1, value2, "pbType");
			return (Criteria) this;
		}

		public Criteria andPbTypeNotBetween(Integer value1, Integer value2) {
			addCriterion("PB_TYPE not between", value1, value2, "pbType");
			return (Criteria) this;
		}

		public Criteria andSubjectTypeIsNull() {
			addCriterion("SUBJECT_TYPE is null");
			return (Criteria) this;
		}

		public Criteria andSubjectTypeIsNotNull() {
			addCriterion("SUBJECT_TYPE is not null");
			return (Criteria) this;
		}

		public Criteria andSubjectTypeEqualTo(Integer value) {
			addCriterion("SUBJECT_TYPE =", value, "subjectType");
			return (Criteria) this;
		}

		public Criteria andSubjectTypeNotEqualTo(Integer value) {
			addCriterion("SUBJECT_TYPE <>", value, "subjectType");
			return (Criteria) this;
		}

		public Criteria andSubjectTypeGreaterThan(Integer value) {
			addCriterion("SUBJECT_TYPE >", value, "subjectType");
			return (Criteria) this;
		}

		public Criteria andSubjectTypeGreaterThanOrEqualTo(Integer value) {
			addCriterion("SUBJECT_TYPE >=", value, "subjectType");
			return (Criteria) this;
		}

		public Criteria andSubjectTypeLessThan(Integer value) {
			addCriterion("SUBJECT_TYPE <", value, "subjectType");
			return (Criteria) this;
		}

		public Criteria andSubjectTypeLessThanOrEqualTo(Integer value) {
			addCriterion("SUBJECT_TYPE <=", value, "subjectType");
			return (Criteria) this;
		}

		public Criteria andSubjectTypeIn(List<Integer> values) {
			addCriterion("SUBJECT_TYPE in", values, "subjectType");
			return (Criteria) this;
		}

		public Criteria andSubjectTypeNotIn(List<Integer> values) {
			addCriterion("SUBJECT_TYPE not in", values, "subjectType");
			return (Criteria) this;
		}

		public Criteria andSubjectTypeBetween(Integer value1, Integer value2) {
			addCriterion("SUBJECT_TYPE between", value1, value2, "subjectType");
			return (Criteria) this;
		}

		public Criteria andSubjectTypeNotBetween(Integer value1, Integer value2) {
			addCriterion("SUBJECT_TYPE not between", value1, value2, "subjectType");
			return (Criteria) this;
		}

		public Criteria andPsiBriefIsNull() {
			addCriterion("PSI_BRIEF is null");
			return (Criteria) this;
		}

		public Criteria andPsiBriefIsNotNull() {
			addCriterion("PSI_BRIEF is not null");
			return (Criteria) this;
		}

		public Criteria andPsiBriefEqualTo(String value) {
			addCriterion("PSI_BRIEF =", value, "psiBrief");
			return (Criteria) this;
		}

		public Criteria andPsiBriefNotEqualTo(String value) {
			addCriterion("PSI_BRIEF <>", value, "psiBrief");
			return (Criteria) this;
		}

		public Criteria andPsiBriefGreaterThan(String value) {
			addCriterion("PSI_BRIEF >", value, "psiBrief");
			return (Criteria) this;
		}

		public Criteria andPsiBriefGreaterThanOrEqualTo(String value) {
			addCriterion("PSI_BRIEF >=", value, "psiBrief");
			return (Criteria) this;
		}

		public Criteria andPsiBriefLessThan(String value) {
			addCriterion("PSI_BRIEF <", value, "psiBrief");
			return (Criteria) this;
		}

		public Criteria andPsiBriefLessThanOrEqualTo(String value) {
			addCriterion("PSI_BRIEF <=", value, "psiBrief");
			return (Criteria) this;
		}

		public Criteria andPsiBriefLike(String value) {
			addCriterion("PSI_BRIEF like", value, "psiBrief");
			return (Criteria) this;
		}

		public Criteria andPsiBriefNotLike(String value) {
			addCriterion("PSI_BRIEF not like", value, "psiBrief");
			return (Criteria) this;
		}

		public Criteria andPsiBriefIn(List<String> values) {
			addCriterion("PSI_BRIEF in", values, "psiBrief");
			return (Criteria) this;
		}

		public Criteria andPsiBriefNotIn(List<String> values) {
			addCriterion("PSI_BRIEF not in", values, "psiBrief");
			return (Criteria) this;
		}

		public Criteria andPsiBriefBetween(String value1, String value2) {
			addCriterion("PSI_BRIEF between", value1, value2, "psiBrief");
			return (Criteria) this;
		}

		public Criteria andPsiBriefNotBetween(String value1, String value2) {
			addCriterion("PSI_BRIEF not between", value1, value2, "psiBrief");
			return (Criteria) this;
		}

		public Criteria andPsiReasonIsNull() {
			addCriterion("PSI_REASON is null");
			return (Criteria) this;
		}

		public Criteria andPsiReasonIsNotNull() {
			addCriterion("PSI_REASON is not null");
			return (Criteria) this;
		}

		public Criteria andPsiReasonEqualTo(String value) {
			addCriterion("PSI_REASON =", value, "psiReason");
			return (Criteria) this;
		}

		public Criteria andPsiReasonNotEqualTo(String value) {
			addCriterion("PSI_REASON <>", value, "psiReason");
			return (Criteria) this;
		}

		public Criteria andPsiReasonGreaterThan(String value) {
			addCriterion("PSI_REASON >", value, "psiReason");
			return (Criteria) this;
		}

		public Criteria andPsiReasonGreaterThanOrEqualTo(String value) {
			addCriterion("PSI_REASON >=", value, "psiReason");
			return (Criteria) this;
		}

		public Criteria andPsiReasonLessThan(String value) {
			addCriterion("PSI_REASON <", value, "psiReason");
			return (Criteria) this;
		}

		public Criteria andPsiReasonLessThanOrEqualTo(String value) {
			addCriterion("PSI_REASON <=", value, "psiReason");
			return (Criteria) this;
		}

		public Criteria andPsiReasonLike(String value) {
			addCriterion("PSI_REASON like", value, "psiReason");
			return (Criteria) this;
		}

		public Criteria andPsiReasonNotLike(String value) {
			addCriterion("PSI_REASON not like", value, "psiReason");
			return (Criteria) this;
		}

		public Criteria andPsiReasonIn(List<String> values) {
			addCriterion("PSI_REASON in", values, "psiReason");
			return (Criteria) this;
		}

		public Criteria andPsiReasonNotIn(List<String> values) {
			addCriterion("PSI_REASON not in", values, "psiReason");
			return (Criteria) this;
		}

		public Criteria andPsiReasonBetween(String value1, String value2) {
			addCriterion("PSI_REASON between", value1, value2, "psiReason");
			return (Criteria) this;
		}

		public Criteria andPsiReasonNotBetween(String value1, String value2) {
			addCriterion("PSI_REASON not between", value1, value2, "psiReason");
			return (Criteria) this;
		}

		public Criteria andPsiContentIsNull() {
			addCriterion("PSI_CONTENT is null");
			return (Criteria) this;
		}

		public Criteria andPsiContentIsNotNull() {
			addCriterion("PSI_CONTENT is not null");
			return (Criteria) this;
		}

		public Criteria andPsiContentEqualTo(String value) {
			addCriterion("PSI_CONTENT =", value, "psiContent");
			return (Criteria) this;
		}

		public Criteria andPsiContentNotEqualTo(String value) {
			addCriterion("PSI_CONTENT <>", value, "psiContent");
			return (Criteria) this;
		}

		public Criteria andPsiContentGreaterThan(String value) {
			addCriterion("PSI_CONTENT >", value, "psiContent");
			return (Criteria) this;
		}

		public Criteria andPsiContentGreaterThanOrEqualTo(String value) {
			addCriterion("PSI_CONTENT >=", value, "psiContent");
			return (Criteria) this;
		}

		public Criteria andPsiContentLessThan(String value) {
			addCriterion("PSI_CONTENT <", value, "psiContent");
			return (Criteria) this;
		}

		public Criteria andPsiContentLessThanOrEqualTo(String value) {
			addCriterion("PSI_CONTENT <=", value, "psiContent");
			return (Criteria) this;
		}

		public Criteria andPsiContentLike(String value) {
			addCriterion("PSI_CONTENT like", value, "psiContent");
			return (Criteria) this;
		}

		public Criteria andPsiContentNotLike(String value) {
			addCriterion("PSI_CONTENT not like", value, "psiContent");
			return (Criteria) this;
		}

		public Criteria andPsiContentIn(List<String> values) {
			addCriterion("PSI_CONTENT in", values, "psiContent");
			return (Criteria) this;
		}

		public Criteria andPsiContentNotIn(List<String> values) {
			addCriterion("PSI_CONTENT not in", values, "psiContent");
			return (Criteria) this;
		}

		public Criteria andPsiContentBetween(String value1, String value2) {
			addCriterion("PSI_CONTENT between", value1, value2, "psiContent");
			return (Criteria) this;
		}

		public Criteria andPsiContentNotBetween(String value1, String value2) {
			addCriterion("PSI_CONTENT not between", value1, value2, "psiContent");
			return (Criteria) this;
		}

		public Criteria andPsiFeatureIsNull() {
			addCriterion("PSI_FEATURE is null");
			return (Criteria) this;
		}

		public Criteria andPsiFeatureIsNotNull() {
			addCriterion("PSI_FEATURE is not null");
			return (Criteria) this;
		}

		public Criteria andPsiFeatureEqualTo(String value) {
			addCriterion("PSI_FEATURE =", value, "psiFeature");
			return (Criteria) this;
		}

		public Criteria andPsiFeatureNotEqualTo(String value) {
			addCriterion("PSI_FEATURE <>", value, "psiFeature");
			return (Criteria) this;
		}

		public Criteria andPsiFeatureGreaterThan(String value) {
			addCriterion("PSI_FEATURE >", value, "psiFeature");
			return (Criteria) this;
		}

		public Criteria andPsiFeatureGreaterThanOrEqualTo(String value) {
			addCriterion("PSI_FEATURE >=", value, "psiFeature");
			return (Criteria) this;
		}

		public Criteria andPsiFeatureLessThan(String value) {
			addCriterion("PSI_FEATURE <", value, "psiFeature");
			return (Criteria) this;
		}

		public Criteria andPsiFeatureLessThanOrEqualTo(String value) {
			addCriterion("PSI_FEATURE <=", value, "psiFeature");
			return (Criteria) this;
		}

		public Criteria andPsiFeatureLike(String value) {
			addCriterion("PSI_FEATURE like", value, "psiFeature");
			return (Criteria) this;
		}

		public Criteria andPsiFeatureNotLike(String value) {
			addCriterion("PSI_FEATURE not like", value, "psiFeature");
			return (Criteria) this;
		}

		public Criteria andPsiFeatureIn(List<String> values) {
			addCriterion("PSI_FEATURE in", values, "psiFeature");
			return (Criteria) this;
		}

		public Criteria andPsiFeatureNotIn(List<String> values) {
			addCriterion("PSI_FEATURE not in", values, "psiFeature");
			return (Criteria) this;
		}

		public Criteria andPsiFeatureBetween(String value1, String value2) {
			addCriterion("PSI_FEATURE between", value1, value2, "psiFeature");
			return (Criteria) this;
		}

		public Criteria andPsiFeatureNotBetween(String value1, String value2) {
			addCriterion("PSI_FEATURE not between", value1, value2, "psiFeature");
			return (Criteria) this;
		}

		public Criteria andPsiPlanIsNull() {
			addCriterion("PSI_PLAN is null");
			return (Criteria) this;
		}

		public Criteria andPsiPlanIsNotNull() {
			addCriterion("PSI_PLAN is not null");
			return (Criteria) this;
		}

		public Criteria andPsiPlanEqualTo(String value) {
			addCriterion("PSI_PLAN =", value, "psiPlan");
			return (Criteria) this;
		}

		public Criteria andPsiPlanNotEqualTo(String value) {
			addCriterion("PSI_PLAN <>", value, "psiPlan");
			return (Criteria) this;
		}

		public Criteria andPsiPlanGreaterThan(String value) {
			addCriterion("PSI_PLAN >", value, "psiPlan");
			return (Criteria) this;
		}

		public Criteria andPsiPlanGreaterThanOrEqualTo(String value) {
			addCriterion("PSI_PLAN >=", value, "psiPlan");
			return (Criteria) this;
		}

		public Criteria andPsiPlanLessThan(String value) {
			addCriterion("PSI_PLAN <", value, "psiPlan");
			return (Criteria) this;
		}

		public Criteria andPsiPlanLessThanOrEqualTo(String value) {
			addCriterion("PSI_PLAN <=", value, "psiPlan");
			return (Criteria) this;
		}

		public Criteria andPsiPlanLike(String value) {
			addCriterion("PSI_PLAN like", value, "psiPlan");
			return (Criteria) this;
		}

		public Criteria andPsiPlanNotLike(String value) {
			addCriterion("PSI_PLAN not like", value, "psiPlan");
			return (Criteria) this;
		}

		public Criteria andPsiPlanIn(List<String> values) {
			addCriterion("PSI_PLAN in", values, "psiPlan");
			return (Criteria) this;
		}

		public Criteria andPsiPlanNotIn(List<String> values) {
			addCriterion("PSI_PLAN not in", values, "psiPlan");
			return (Criteria) this;
		}

		public Criteria andPsiPlanBetween(String value1, String value2) {
			addCriterion("PSI_PLAN between", value1, value2, "psiPlan");
			return (Criteria) this;
		}

		public Criteria andPsiPlanNotBetween(String value1, String value2) {
			addCriterion("PSI_PLAN not between", value1, value2, "psiPlan");
			return (Criteria) this;
		}

		public Criteria andPsiResultIsNull() {
			addCriterion("PSI_RESULT is null");
			return (Criteria) this;
		}

		public Criteria andPsiResultIsNotNull() {
			addCriterion("PSI_RESULT is not null");
			return (Criteria) this;
		}

		public Criteria andPsiResultEqualTo(String value) {
			addCriterion("PSI_RESULT =", value, "psiResult");
			return (Criteria) this;
		}

		public Criteria andPsiResultNotEqualTo(String value) {
			addCriterion("PSI_RESULT <>", value, "psiResult");
			return (Criteria) this;
		}

		public Criteria andPsiResultGreaterThan(String value) {
			addCriterion("PSI_RESULT >", value, "psiResult");
			return (Criteria) this;
		}

		public Criteria andPsiResultGreaterThanOrEqualTo(String value) {
			addCriterion("PSI_RESULT >=", value, "psiResult");
			return (Criteria) this;
		}

		public Criteria andPsiResultLessThan(String value) {
			addCriterion("PSI_RESULT <", value, "psiResult");
			return (Criteria) this;
		}

		public Criteria andPsiResultLessThanOrEqualTo(String value) {
			addCriterion("PSI_RESULT <=", value, "psiResult");
			return (Criteria) this;
		}

		public Criteria andPsiResultLike(String value) {
			addCriterion("PSI_RESULT like", value, "psiResult");
			return (Criteria) this;
		}

		public Criteria andPsiResultNotLike(String value) {
			addCriterion("PSI_RESULT not like", value, "psiResult");
			return (Criteria) this;
		}

		public Criteria andPsiResultIn(List<String> values) {
			addCriterion("PSI_RESULT in", values, "psiResult");
			return (Criteria) this;
		}

		public Criteria andPsiResultNotIn(List<String> values) {
			addCriterion("PSI_RESULT not in", values, "psiResult");
			return (Criteria) this;
		}

		public Criteria andPsiResultBetween(String value1, String value2) {
			addCriterion("PSI_RESULT between", value1, value2, "psiResult");
			return (Criteria) this;
		}

		public Criteria andPsiResultNotBetween(String value1, String value2) {
			addCriterion("PSI_RESULT not between", value1, value2, "psiResult");
			return (Criteria) this;
		}

		public Criteria andUIdIsNull() {
			addCriterion("U_ID is null");
			return (Criteria) this;
		}

		public Criteria andUIdIsNotNull() {
			addCriterion("U_ID is not null");
			return (Criteria) this;
		}

		public Criteria andUIdEqualTo(Integer value) {
			addCriterion("U_ID =", value, "uId");
			return (Criteria) this;
		}

		public Criteria andUIdNotEqualTo(Integer value) {
			addCriterion("U_ID <>", value, "uId");
			return (Criteria) this;
		}

		public Criteria andUIdGreaterThan(Integer value) {
			addCriterion("U_ID >", value, "uId");
			return (Criteria) this;
		}

		public Criteria andUIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("U_ID >=", value, "uId");
			return (Criteria) this;
		}

		public Criteria andUIdLessThan(Integer value) {
			addCriterion("U_ID <", value, "uId");
			return (Criteria) this;
		}

		public Criteria andUIdLessThanOrEqualTo(Integer value) {
			addCriterion("U_ID <=", value, "uId");
			return (Criteria) this;
		}

		public Criteria andUIdIn(List<Integer> values) {
			addCriterion("U_ID in", values, "uId");
			return (Criteria) this;
		}

		public Criteria andUIdNotIn(List<Integer> values) {
			addCriterion("U_ID not in", values, "uId");
			return (Criteria) this;
		}

		public Criteria andUIdBetween(Integer value1, Integer value2) {
			addCriterion("U_ID between", value1, value2, "uId");
			return (Criteria) this;
		}

		public Criteria andUIdNotBetween(Integer value1, Integer value2) {
			addCriterion("U_ID not between", value1, value2, "uId");
			return (Criteria) this;
		}

		public Criteria andUTypeIsNull() {
			addCriterion("U_TYPE is null");
			return (Criteria) this;
		}

		public Criteria andUTypeIsNotNull() {
			addCriterion("U_TYPE is not null");
			return (Criteria) this;
		}

		public Criteria andUTypeEqualTo(Integer value) {
			addCriterion("U_TYPE =", value, "uType");
			return (Criteria) this;
		}

		public Criteria andUTypeNotEqualTo(Integer value) {
			addCriterion("U_TYPE <>", value, "uType");
			return (Criteria) this;
		}

		public Criteria andUTypeGreaterThan(Integer value) {
			addCriterion("U_TYPE >", value, "uType");
			return (Criteria) this;
		}

		public Criteria andUTypeGreaterThanOrEqualTo(Integer value) {
			addCriterion("U_TYPE >=", value, "uType");
			return (Criteria) this;
		}

		public Criteria andUTypeLessThan(Integer value) {
			addCriterion("U_TYPE <", value, "uType");
			return (Criteria) this;
		}

		public Criteria andUTypeLessThanOrEqualTo(Integer value) {
			addCriterion("U_TYPE <=", value, "uType");
			return (Criteria) this;
		}

		public Criteria andUTypeIn(List<Integer> values) {
			addCriterion("U_TYPE in", values, "uType");
			return (Criteria) this;
		}

		public Criteria andUTypeNotIn(List<Integer> values) {
			addCriterion("U_TYPE not in", values, "uType");
			return (Criteria) this;
		}

		public Criteria andUTypeBetween(Integer value1, Integer value2) {
			addCriterion("U_TYPE between", value1, value2, "uType");
			return (Criteria) this;
		}

		public Criteria andUTypeNotBetween(Integer value1, Integer value2) {
			addCriterion("U_TYPE not between", value1, value2, "uType");
			return (Criteria) this;
		}

		public Criteria andPsiOStatusIsNull() {
			addCriterion("PSI_O_STATUS is null");
			return (Criteria) this;
		}

		public Criteria andPsiOStatusIsNotNull() {
			addCriterion("PSI_O_STATUS is not null");
			return (Criteria) this;
		}

		public Criteria andPsiOStatusEqualTo(Integer value) {
			addCriterion("PSI_O_STATUS =", value, "psiOStatus");
			return (Criteria) this;
		}

		public Criteria andPsiOStatusNotEqualTo(Integer value) {
			addCriterion("PSI_O_STATUS <>", value, "psiOStatus");
			return (Criteria) this;
		}

		public Criteria andPsiOStatusGreaterThan(Integer value) {
			addCriterion("PSI_O_STATUS >", value, "psiOStatus");
			return (Criteria) this;
		}

		public Criteria andPsiOStatusGreaterThanOrEqualTo(Integer value) {
			addCriterion("PSI_O_STATUS >=", value, "psiOStatus");
			return (Criteria) this;
		}

		public Criteria andPsiOStatusLessThan(Integer value) {
			addCriterion("PSI_O_STATUS <", value, "psiOStatus");
			return (Criteria) this;
		}

		public Criteria andPsiOStatusLessThanOrEqualTo(Integer value) {
			addCriterion("PSI_O_STATUS <=", value, "psiOStatus");
			return (Criteria) this;
		}

		public Criteria andPsiOStatusIn(List<Integer> values) {
			addCriterion("PSI_O_STATUS in", values, "psiOStatus");
			return (Criteria) this;
		}

		public Criteria andPsiOStatusNotIn(List<Integer> values) {
			addCriterion("PSI_O_STATUS not in", values, "psiOStatus");
			return (Criteria) this;
		}

		public Criteria andPsiOStatusBetween(Integer value1, Integer value2) {
			addCriterion("PSI_O_STATUS between", value1, value2, "psiOStatus");
			return (Criteria) this;
		}

		public Criteria andPsiOStatusNotBetween(Integer value1, Integer value2) {
			addCriterion("PSI_O_STATUS not between", value1, value2, "psiOStatus");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table project_start_view
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table project_start_view
     *
     * @mbg.generated do_not_delete_during_merge Sun May 06 20:50:13 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}