package com.plm.model;

import java.util.Date;

public class ProjectProcessInfo {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column project_process_info.PPI_ID
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	private Integer ppiId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column project_process_info.PB_ID
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	private Integer pbId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column project_process_info.PPI_CREATE_TIME
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	private Date ppiCreateTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column project_process_info.PPI_EDIT_TIME
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	private Date ppiEditTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column project_process_info.PPI_TYPE
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	private Integer ppiType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column project_process_info.PMI_CONTENT
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	private String pmiContent;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column project_process_info.PMI_ISSUE
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	private String pmiIssue;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column project_process_info.PEI_LEVEL
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	private Integer peiLevel;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column project_process_info.PEI_MISSION
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	private String peiMission;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column project_process_info.PEI_OPOINION
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	private String peiOpoinion;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column project_process_info.POI_TYPE
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	private Integer poiType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column project_process_info.POI_CONTENT
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	private String poiContent;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column project_process_info.PPI_ID
	 * @return  the value of project_process_info.PPI_ID
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public Integer getPpiId() {
		return ppiId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column project_process_info.PPI_ID
	 * @param ppiId  the value for project_process_info.PPI_ID
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public void setPpiId(Integer ppiId) {
		this.ppiId = ppiId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column project_process_info.PB_ID
	 * @return  the value of project_process_info.PB_ID
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public Integer getPbId() {
		return pbId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column project_process_info.PB_ID
	 * @param pbId  the value for project_process_info.PB_ID
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public void setPbId(Integer pbId) {
		this.pbId = pbId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column project_process_info.PPI_CREATE_TIME
	 * @return  the value of project_process_info.PPI_CREATE_TIME
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public Date getPpiCreateTime() {
		return ppiCreateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column project_process_info.PPI_CREATE_TIME
	 * @param ppiCreateTime  the value for project_process_info.PPI_CREATE_TIME
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public void setPpiCreateTime(Date ppiCreateTime) {
		this.ppiCreateTime = ppiCreateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column project_process_info.PPI_EDIT_TIME
	 * @return  the value of project_process_info.PPI_EDIT_TIME
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public Date getPpiEditTime() {
		return ppiEditTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column project_process_info.PPI_EDIT_TIME
	 * @param ppiEditTime  the value for project_process_info.PPI_EDIT_TIME
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public void setPpiEditTime(Date ppiEditTime) {
		this.ppiEditTime = ppiEditTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column project_process_info.PPI_TYPE
	 * @return  the value of project_process_info.PPI_TYPE
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public Integer getPpiType() {
		return ppiType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column project_process_info.PPI_TYPE
	 * @param ppiType  the value for project_process_info.PPI_TYPE
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public void setPpiType(Integer ppiType) {
		this.ppiType = ppiType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column project_process_info.PMI_CONTENT
	 * @return  the value of project_process_info.PMI_CONTENT
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public String getPmiContent() {
		return pmiContent;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column project_process_info.PMI_CONTENT
	 * @param pmiContent  the value for project_process_info.PMI_CONTENT
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public void setPmiContent(String pmiContent) {
		this.pmiContent = pmiContent;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column project_process_info.PMI_ISSUE
	 * @return  the value of project_process_info.PMI_ISSUE
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public String getPmiIssue() {
		return pmiIssue;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column project_process_info.PMI_ISSUE
	 * @param pmiIssue  the value for project_process_info.PMI_ISSUE
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public void setPmiIssue(String pmiIssue) {
		this.pmiIssue = pmiIssue;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column project_process_info.PEI_LEVEL
	 * @return  the value of project_process_info.PEI_LEVEL
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public Integer getPeiLevel() {
		return peiLevel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column project_process_info.PEI_LEVEL
	 * @param peiLevel  the value for project_process_info.PEI_LEVEL
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public void setPeiLevel(Integer peiLevel) {
		this.peiLevel = peiLevel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column project_process_info.PEI_MISSION
	 * @return  the value of project_process_info.PEI_MISSION
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public String getPeiMission() {
		return peiMission;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column project_process_info.PEI_MISSION
	 * @param peiMission  the value for project_process_info.PEI_MISSION
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public void setPeiMission(String peiMission) {
		this.peiMission = peiMission;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column project_process_info.PEI_OPOINION
	 * @return  the value of project_process_info.PEI_OPOINION
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public String getPeiOpoinion() {
		return peiOpoinion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column project_process_info.PEI_OPOINION
	 * @param peiOpoinion  the value for project_process_info.PEI_OPOINION
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public void setPeiOpoinion(String peiOpoinion) {
		this.peiOpoinion = peiOpoinion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column project_process_info.POI_TYPE
	 * @return  the value of project_process_info.POI_TYPE
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public Integer getPoiType() {
		return poiType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column project_process_info.POI_TYPE
	 * @param poiType  the value for project_process_info.POI_TYPE
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public void setPoiType(Integer poiType) {
		this.poiType = poiType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column project_process_info.POI_CONTENT
	 * @return  the value of project_process_info.POI_CONTENT
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public String getPoiContent() {
		return poiContent;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column project_process_info.POI_CONTENT
	 * @param poiContent  the value for project_process_info.POI_CONTENT
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public void setPoiContent(String poiContent) {
		this.poiContent = poiContent;
	}
}