package com.plm.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class ProjectBaseViewExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table project_base_view
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table project_base_view
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table project_base_view
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table project_base_view
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public ProjectBaseViewExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table project_base_view
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table project_base_view
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table project_base_view
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table project_base_view
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table project_base_view
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table project_base_view
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table project_base_view
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table project_base_view
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table project_base_view
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table project_base_view
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table project_base_view
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		protected void addCriterionForJDBCDate(String condition, Date value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			addCriterion(condition, new java.sql.Date(value.getTime()), property);
		}

		protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
			if (values == null || values.size() == 0) {
				throw new RuntimeException("Value list for " + property + " cannot be null or empty");
			}
			List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
			Iterator<Date> iter = values.iterator();
			while (iter.hasNext()) {
				dateList.add(new java.sql.Date(iter.next().getTime()));
			}
			addCriterion(condition, dateList, property);
		}

		protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
		}

		public Criteria andPbIdIsNull() {
			addCriterion("PB_ID is null");
			return (Criteria) this;
		}

		public Criteria andPbIdIsNotNull() {
			addCriterion("PB_ID is not null");
			return (Criteria) this;
		}

		public Criteria andPbIdEqualTo(Integer value) {
			addCriterion("PB_ID =", value, "pbId");
			return (Criteria) this;
		}

		public Criteria andPbIdNotEqualTo(Integer value) {
			addCriterion("PB_ID <>", value, "pbId");
			return (Criteria) this;
		}

		public Criteria andPbIdGreaterThan(Integer value) {
			addCriterion("PB_ID >", value, "pbId");
			return (Criteria) this;
		}

		public Criteria andPbIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("PB_ID >=", value, "pbId");
			return (Criteria) this;
		}

		public Criteria andPbIdLessThan(Integer value) {
			addCriterion("PB_ID <", value, "pbId");
			return (Criteria) this;
		}

		public Criteria andPbIdLessThanOrEqualTo(Integer value) {
			addCriterion("PB_ID <=", value, "pbId");
			return (Criteria) this;
		}

		public Criteria andPbIdIn(List<Integer> values) {
			addCriterion("PB_ID in", values, "pbId");
			return (Criteria) this;
		}

		public Criteria andPbIdNotIn(List<Integer> values) {
			addCriterion("PB_ID not in", values, "pbId");
			return (Criteria) this;
		}

		public Criteria andPbIdBetween(Integer value1, Integer value2) {
			addCriterion("PB_ID between", value1, value2, "pbId");
			return (Criteria) this;
		}

		public Criteria andPbIdNotBetween(Integer value1, Integer value2) {
			addCriterion("PB_ID not between", value1, value2, "pbId");
			return (Criteria) this;
		}

		public Criteria andUIdIsNull() {
			addCriterion("U_ID is null");
			return (Criteria) this;
		}

		public Criteria andUIdIsNotNull() {
			addCriterion("U_ID is not null");
			return (Criteria) this;
		}

		public Criteria andUIdEqualTo(Integer value) {
			addCriterion("U_ID =", value, "uId");
			return (Criteria) this;
		}

		public Criteria andUIdNotEqualTo(Integer value) {
			addCriterion("U_ID <>", value, "uId");
			return (Criteria) this;
		}

		public Criteria andUIdGreaterThan(Integer value) {
			addCriterion("U_ID >", value, "uId");
			return (Criteria) this;
		}

		public Criteria andUIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("U_ID >=", value, "uId");
			return (Criteria) this;
		}

		public Criteria andUIdLessThan(Integer value) {
			addCriterion("U_ID <", value, "uId");
			return (Criteria) this;
		}

		public Criteria andUIdLessThanOrEqualTo(Integer value) {
			addCriterion("U_ID <=", value, "uId");
			return (Criteria) this;
		}

		public Criteria andUIdIn(List<Integer> values) {
			addCriterion("U_ID in", values, "uId");
			return (Criteria) this;
		}

		public Criteria andUIdNotIn(List<Integer> values) {
			addCriterion("U_ID not in", values, "uId");
			return (Criteria) this;
		}

		public Criteria andUIdBetween(Integer value1, Integer value2) {
			addCriterion("U_ID between", value1, value2, "uId");
			return (Criteria) this;
		}

		public Criteria andUIdNotBetween(Integer value1, Integer value2) {
			addCriterion("U_ID not between", value1, value2, "uId");
			return (Criteria) this;
		}

		public Criteria andUNameIsNull() {
			addCriterion("U_NAME is null");
			return (Criteria) this;
		}

		public Criteria andUNameIsNotNull() {
			addCriterion("U_NAME is not null");
			return (Criteria) this;
		}

		public Criteria andUNameEqualTo(String value) {
			addCriterion("U_NAME =", value, "uName");
			return (Criteria) this;
		}

		public Criteria andUNameNotEqualTo(String value) {
			addCriterion("U_NAME <>", value, "uName");
			return (Criteria) this;
		}

		public Criteria andUNameGreaterThan(String value) {
			addCriterion("U_NAME >", value, "uName");
			return (Criteria) this;
		}

		public Criteria andUNameGreaterThanOrEqualTo(String value) {
			addCriterion("U_NAME >=", value, "uName");
			return (Criteria) this;
		}

		public Criteria andUNameLessThan(String value) {
			addCriterion("U_NAME <", value, "uName");
			return (Criteria) this;
		}

		public Criteria andUNameLessThanOrEqualTo(String value) {
			addCriterion("U_NAME <=", value, "uName");
			return (Criteria) this;
		}

		public Criteria andUNameLike(String value) {
			addCriterion("U_NAME like", value, "uName");
			return (Criteria) this;
		}

		public Criteria andUNameNotLike(String value) {
			addCriterion("U_NAME not like", value, "uName");
			return (Criteria) this;
		}

		public Criteria andUNameIn(List<String> values) {
			addCriterion("U_NAME in", values, "uName");
			return (Criteria) this;
		}

		public Criteria andUNameNotIn(List<String> values) {
			addCriterion("U_NAME not in", values, "uName");
			return (Criteria) this;
		}

		public Criteria andUNameBetween(String value1, String value2) {
			addCriterion("U_NAME between", value1, value2, "uName");
			return (Criteria) this;
		}

		public Criteria andUNameNotBetween(String value1, String value2) {
			addCriterion("U_NAME not between", value1, value2, "uName");
			return (Criteria) this;
		}

		public Criteria andURealnameIsNull() {
			addCriterion("U_REALNAME is null");
			return (Criteria) this;
		}

		public Criteria andURealnameIsNotNull() {
			addCriterion("U_REALNAME is not null");
			return (Criteria) this;
		}

		public Criteria andURealnameEqualTo(String value) {
			addCriterion("U_REALNAME =", value, "uRealname");
			return (Criteria) this;
		}

		public Criteria andURealnameNotEqualTo(String value) {
			addCriterion("U_REALNAME <>", value, "uRealname");
			return (Criteria) this;
		}

		public Criteria andURealnameGreaterThan(String value) {
			addCriterion("U_REALNAME >", value, "uRealname");
			return (Criteria) this;
		}

		public Criteria andURealnameGreaterThanOrEqualTo(String value) {
			addCriterion("U_REALNAME >=", value, "uRealname");
			return (Criteria) this;
		}

		public Criteria andURealnameLessThan(String value) {
			addCriterion("U_REALNAME <", value, "uRealname");
			return (Criteria) this;
		}

		public Criteria andURealnameLessThanOrEqualTo(String value) {
			addCriterion("U_REALNAME <=", value, "uRealname");
			return (Criteria) this;
		}

		public Criteria andURealnameLike(String value) {
			addCriterion("U_REALNAME like", value, "uRealname");
			return (Criteria) this;
		}

		public Criteria andURealnameNotLike(String value) {
			addCriterion("U_REALNAME not like", value, "uRealname");
			return (Criteria) this;
		}

		public Criteria andURealnameIn(List<String> values) {
			addCriterion("U_REALNAME in", values, "uRealname");
			return (Criteria) this;
		}

		public Criteria andURealnameNotIn(List<String> values) {
			addCriterion("U_REALNAME not in", values, "uRealname");
			return (Criteria) this;
		}

		public Criteria andURealnameBetween(String value1, String value2) {
			addCriterion("U_REALNAME between", value1, value2, "uRealname");
			return (Criteria) this;
		}

		public Criteria andURealnameNotBetween(String value1, String value2) {
			addCriterion("U_REALNAME not between", value1, value2, "uRealname");
			return (Criteria) this;
		}

		public Criteria andPbCreateTimeIsNull() {
			addCriterion("PB_CREATE_TIME is null");
			return (Criteria) this;
		}

		public Criteria andPbCreateTimeIsNotNull() {
			addCriterion("PB_CREATE_TIME is not null");
			return (Criteria) this;
		}

		public Criteria andPbCreateTimeEqualTo(Date value) {
			addCriterion("PB_CREATE_TIME =", value, "pbCreateTime");
			return (Criteria) this;
		}

		public Criteria andPbCreateTimeNotEqualTo(Date value) {
			addCriterion("PB_CREATE_TIME <>", value, "pbCreateTime");
			return (Criteria) this;
		}

		public Criteria andPbCreateTimeGreaterThan(Date value) {
			addCriterion("PB_CREATE_TIME >", value, "pbCreateTime");
			return (Criteria) this;
		}

		public Criteria andPbCreateTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("PB_CREATE_TIME >=", value, "pbCreateTime");
			return (Criteria) this;
		}

		public Criteria andPbCreateTimeLessThan(Date value) {
			addCriterion("PB_CREATE_TIME <", value, "pbCreateTime");
			return (Criteria) this;
		}

		public Criteria andPbCreateTimeLessThanOrEqualTo(Date value) {
			addCriterion("PB_CREATE_TIME <=", value, "pbCreateTime");
			return (Criteria) this;
		}

		public Criteria andPbCreateTimeIn(List<Date> values) {
			addCriterion("PB_CREATE_TIME in", values, "pbCreateTime");
			return (Criteria) this;
		}

		public Criteria andPbCreateTimeNotIn(List<Date> values) {
			addCriterion("PB_CREATE_TIME not in", values, "pbCreateTime");
			return (Criteria) this;
		}

		public Criteria andPbCreateTimeBetween(Date value1, Date value2) {
			addCriterion("PB_CREATE_TIME between", value1, value2, "pbCreateTime");
			return (Criteria) this;
		}

		public Criteria andPbCreateTimeNotBetween(Date value1, Date value2) {
			addCriterion("PB_CREATE_TIME not between", value1, value2, "pbCreateTime");
			return (Criteria) this;
		}

		public Criteria andPbEditTimeIsNull() {
			addCriterion("PB_EDIT_TIME is null");
			return (Criteria) this;
		}

		public Criteria andPbEditTimeIsNotNull() {
			addCriterion("PB_EDIT_TIME is not null");
			return (Criteria) this;
		}

		public Criteria andPbEditTimeEqualTo(Date value) {
			addCriterion("PB_EDIT_TIME =", value, "pbEditTime");
			return (Criteria) this;
		}

		public Criteria andPbEditTimeNotEqualTo(Date value) {
			addCriterion("PB_EDIT_TIME <>", value, "pbEditTime");
			return (Criteria) this;
		}

		public Criteria andPbEditTimeGreaterThan(Date value) {
			addCriterion("PB_EDIT_TIME >", value, "pbEditTime");
			return (Criteria) this;
		}

		public Criteria andPbEditTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("PB_EDIT_TIME >=", value, "pbEditTime");
			return (Criteria) this;
		}

		public Criteria andPbEditTimeLessThan(Date value) {
			addCriterion("PB_EDIT_TIME <", value, "pbEditTime");
			return (Criteria) this;
		}

		public Criteria andPbEditTimeLessThanOrEqualTo(Date value) {
			addCriterion("PB_EDIT_TIME <=", value, "pbEditTime");
			return (Criteria) this;
		}

		public Criteria andPbEditTimeIn(List<Date> values) {
			addCriterion("PB_EDIT_TIME in", values, "pbEditTime");
			return (Criteria) this;
		}

		public Criteria andPbEditTimeNotIn(List<Date> values) {
			addCriterion("PB_EDIT_TIME not in", values, "pbEditTime");
			return (Criteria) this;
		}

		public Criteria andPbEditTimeBetween(Date value1, Date value2) {
			addCriterion("PB_EDIT_TIME between", value1, value2, "pbEditTime");
			return (Criteria) this;
		}

		public Criteria andPbEditTimeNotBetween(Date value1, Date value2) {
			addCriterion("PB_EDIT_TIME not between", value1, value2, "pbEditTime");
			return (Criteria) this;
		}

		public Criteria andPbNameIsNull() {
			addCriterion("PB_NAME is null");
			return (Criteria) this;
		}

		public Criteria andPbNameIsNotNull() {
			addCriterion("PB_NAME is not null");
			return (Criteria) this;
		}

		public Criteria andPbNameEqualTo(String value) {
			addCriterion("PB_NAME =", value, "pbName");
			return (Criteria) this;
		}

		public Criteria andPbNameNotEqualTo(String value) {
			addCriterion("PB_NAME <>", value, "pbName");
			return (Criteria) this;
		}

		public Criteria andPbNameGreaterThan(String value) {
			addCriterion("PB_NAME >", value, "pbName");
			return (Criteria) this;
		}

		public Criteria andPbNameGreaterThanOrEqualTo(String value) {
			addCriterion("PB_NAME >=", value, "pbName");
			return (Criteria) this;
		}

		public Criteria andPbNameLessThan(String value) {
			addCriterion("PB_NAME <", value, "pbName");
			return (Criteria) this;
		}

		public Criteria andPbNameLessThanOrEqualTo(String value) {
			addCriterion("PB_NAME <=", value, "pbName");
			return (Criteria) this;
		}

		public Criteria andPbNameLike(String value) {
			addCriterion("PB_NAME like", value, "pbName");
			return (Criteria) this;
		}

		public Criteria andPbNameNotLike(String value) {
			addCriterion("PB_NAME not like", value, "pbName");
			return (Criteria) this;
		}

		public Criteria andPbNameIn(List<String> values) {
			addCriterion("PB_NAME in", values, "pbName");
			return (Criteria) this;
		}

		public Criteria andPbNameNotIn(List<String> values) {
			addCriterion("PB_NAME not in", values, "pbName");
			return (Criteria) this;
		}

		public Criteria andPbNameBetween(String value1, String value2) {
			addCriterion("PB_NAME between", value1, value2, "pbName");
			return (Criteria) this;
		}

		public Criteria andPbNameNotBetween(String value1, String value2) {
			addCriterion("PB_NAME not between", value1, value2, "pbName");
			return (Criteria) this;
		}

		public Criteria andPbLevelIsNull() {
			addCriterion("PB_LEVEL is null");
			return (Criteria) this;
		}

		public Criteria andPbLevelIsNotNull() {
			addCriterion("PB_LEVEL is not null");
			return (Criteria) this;
		}

		public Criteria andPbLevelEqualTo(Integer value) {
			addCriterion("PB_LEVEL =", value, "pbLevel");
			return (Criteria) this;
		}

		public Criteria andPbLevelNotEqualTo(Integer value) {
			addCriterion("PB_LEVEL <>", value, "pbLevel");
			return (Criteria) this;
		}

		public Criteria andPbLevelGreaterThan(Integer value) {
			addCriterion("PB_LEVEL >", value, "pbLevel");
			return (Criteria) this;
		}

		public Criteria andPbLevelGreaterThanOrEqualTo(Integer value) {
			addCriterion("PB_LEVEL >=", value, "pbLevel");
			return (Criteria) this;
		}

		public Criteria andPbLevelLessThan(Integer value) {
			addCriterion("PB_LEVEL <", value, "pbLevel");
			return (Criteria) this;
		}

		public Criteria andPbLevelLessThanOrEqualTo(Integer value) {
			addCriterion("PB_LEVEL <=", value, "pbLevel");
			return (Criteria) this;
		}

		public Criteria andPbLevelIn(List<Integer> values) {
			addCriterion("PB_LEVEL in", values, "pbLevel");
			return (Criteria) this;
		}

		public Criteria andPbLevelNotIn(List<Integer> values) {
			addCriterion("PB_LEVEL not in", values, "pbLevel");
			return (Criteria) this;
		}

		public Criteria andPbLevelBetween(Integer value1, Integer value2) {
			addCriterion("PB_LEVEL between", value1, value2, "pbLevel");
			return (Criteria) this;
		}

		public Criteria andPbLevelNotBetween(Integer value1, Integer value2) {
			addCriterion("PB_LEVEL not between", value1, value2, "pbLevel");
			return (Criteria) this;
		}

		public Criteria andPbTypeIsNull() {
			addCriterion("PB_TYPE is null");
			return (Criteria) this;
		}

		public Criteria andPbTypeIsNotNull() {
			addCriterion("PB_TYPE is not null");
			return (Criteria) this;
		}

		public Criteria andPbTypeEqualTo(Integer value) {
			addCriterion("PB_TYPE =", value, "pbType");
			return (Criteria) this;
		}

		public Criteria andPbTypeNotEqualTo(Integer value) {
			addCriterion("PB_TYPE <>", value, "pbType");
			return (Criteria) this;
		}

		public Criteria andPbTypeGreaterThan(Integer value) {
			addCriterion("PB_TYPE >", value, "pbType");
			return (Criteria) this;
		}

		public Criteria andPbTypeGreaterThanOrEqualTo(Integer value) {
			addCriterion("PB_TYPE >=", value, "pbType");
			return (Criteria) this;
		}

		public Criteria andPbTypeLessThan(Integer value) {
			addCriterion("PB_TYPE <", value, "pbType");
			return (Criteria) this;
		}

		public Criteria andPbTypeLessThanOrEqualTo(Integer value) {
			addCriterion("PB_TYPE <=", value, "pbType");
			return (Criteria) this;
		}

		public Criteria andPbTypeIn(List<Integer> values) {
			addCriterion("PB_TYPE in", values, "pbType");
			return (Criteria) this;
		}

		public Criteria andPbTypeNotIn(List<Integer> values) {
			addCriterion("PB_TYPE not in", values, "pbType");
			return (Criteria) this;
		}

		public Criteria andPbTypeBetween(Integer value1, Integer value2) {
			addCriterion("PB_TYPE between", value1, value2, "pbType");
			return (Criteria) this;
		}

		public Criteria andPbTypeNotBetween(Integer value1, Integer value2) {
			addCriterion("PB_TYPE not between", value1, value2, "pbType");
			return (Criteria) this;
		}

		public Criteria andSubjectTypeIsNull() {
			addCriterion("SUBJECT_TYPE is null");
			return (Criteria) this;
		}

		public Criteria andSubjectTypeIsNotNull() {
			addCriterion("SUBJECT_TYPE is not null");
			return (Criteria) this;
		}

		public Criteria andSubjectTypeEqualTo(Integer value) {
			addCriterion("SUBJECT_TYPE =", value, "subjectType");
			return (Criteria) this;
		}

		public Criteria andSubjectTypeNotEqualTo(Integer value) {
			addCriterion("SUBJECT_TYPE <>", value, "subjectType");
			return (Criteria) this;
		}

		public Criteria andSubjectTypeGreaterThan(Integer value) {
			addCriterion("SUBJECT_TYPE >", value, "subjectType");
			return (Criteria) this;
		}

		public Criteria andSubjectTypeGreaterThanOrEqualTo(Integer value) {
			addCriterion("SUBJECT_TYPE >=", value, "subjectType");
			return (Criteria) this;
		}

		public Criteria andSubjectTypeLessThan(Integer value) {
			addCriterion("SUBJECT_TYPE <", value, "subjectType");
			return (Criteria) this;
		}

		public Criteria andSubjectTypeLessThanOrEqualTo(Integer value) {
			addCriterion("SUBJECT_TYPE <=", value, "subjectType");
			return (Criteria) this;
		}

		public Criteria andSubjectTypeIn(List<Integer> values) {
			addCriterion("SUBJECT_TYPE in", values, "subjectType");
			return (Criteria) this;
		}

		public Criteria andSubjectTypeNotIn(List<Integer> values) {
			addCriterion("SUBJECT_TYPE not in", values, "subjectType");
			return (Criteria) this;
		}

		public Criteria andSubjectTypeBetween(Integer value1, Integer value2) {
			addCriterion("SUBJECT_TYPE between", value1, value2, "subjectType");
			return (Criteria) this;
		}

		public Criteria andSubjectTypeNotBetween(Integer value1, Integer value2) {
			addCriterion("SUBJECT_TYPE not between", value1, value2, "subjectType");
			return (Criteria) this;
		}

		public Criteria andPsiBriefIsNull() {
			addCriterion("PSI_BRIEF is null");
			return (Criteria) this;
		}

		public Criteria andPsiBriefIsNotNull() {
			addCriterion("PSI_BRIEF is not null");
			return (Criteria) this;
		}

		public Criteria andPsiBriefEqualTo(String value) {
			addCriterion("PSI_BRIEF =", value, "psiBrief");
			return (Criteria) this;
		}

		public Criteria andPsiBriefNotEqualTo(String value) {
			addCriterion("PSI_BRIEF <>", value, "psiBrief");
			return (Criteria) this;
		}

		public Criteria andPsiBriefGreaterThan(String value) {
			addCriterion("PSI_BRIEF >", value, "psiBrief");
			return (Criteria) this;
		}

		public Criteria andPsiBriefGreaterThanOrEqualTo(String value) {
			addCriterion("PSI_BRIEF >=", value, "psiBrief");
			return (Criteria) this;
		}

		public Criteria andPsiBriefLessThan(String value) {
			addCriterion("PSI_BRIEF <", value, "psiBrief");
			return (Criteria) this;
		}

		public Criteria andPsiBriefLessThanOrEqualTo(String value) {
			addCriterion("PSI_BRIEF <=", value, "psiBrief");
			return (Criteria) this;
		}

		public Criteria andPsiBriefLike(String value) {
			addCriterion("PSI_BRIEF like", value, "psiBrief");
			return (Criteria) this;
		}

		public Criteria andPsiBriefNotLike(String value) {
			addCriterion("PSI_BRIEF not like", value, "psiBrief");
			return (Criteria) this;
		}

		public Criteria andPsiBriefIn(List<String> values) {
			addCriterion("PSI_BRIEF in", values, "psiBrief");
			return (Criteria) this;
		}

		public Criteria andPsiBriefNotIn(List<String> values) {
			addCriterion("PSI_BRIEF not in", values, "psiBrief");
			return (Criteria) this;
		}

		public Criteria andPsiBriefBetween(String value1, String value2) {
			addCriterion("PSI_BRIEF between", value1, value2, "psiBrief");
			return (Criteria) this;
		}

		public Criteria andPsiBriefNotBetween(String value1, String value2) {
			addCriterion("PSI_BRIEF not between", value1, value2, "psiBrief");
			return (Criteria) this;
		}

		public Criteria andPoiOStatusIsNull() {
			addCriterion("POI_O_STATUS is null");
			return (Criteria) this;
		}

		public Criteria andPoiOStatusIsNotNull() {
			addCriterion("POI_O_STATUS is not null");
			return (Criteria) this;
		}

		public Criteria andPoiOStatusEqualTo(Integer value) {
			addCriterion("POI_O_STATUS =", value, "poiOStatus");
			return (Criteria) this;
		}

		public Criteria andPoiOStatusNotEqualTo(Integer value) {
			addCriterion("POI_O_STATUS <>", value, "poiOStatus");
			return (Criteria) this;
		}

		public Criteria andPoiOStatusGreaterThan(Integer value) {
			addCriterion("POI_O_STATUS >", value, "poiOStatus");
			return (Criteria) this;
		}

		public Criteria andPoiOStatusGreaterThanOrEqualTo(Integer value) {
			addCriterion("POI_O_STATUS >=", value, "poiOStatus");
			return (Criteria) this;
		}

		public Criteria andPoiOStatusLessThan(Integer value) {
			addCriterion("POI_O_STATUS <", value, "poiOStatus");
			return (Criteria) this;
		}

		public Criteria andPoiOStatusLessThanOrEqualTo(Integer value) {
			addCriterion("POI_O_STATUS <=", value, "poiOStatus");
			return (Criteria) this;
		}

		public Criteria andPoiOStatusIn(List<Integer> values) {
			addCriterion("POI_O_STATUS in", values, "poiOStatus");
			return (Criteria) this;
		}

		public Criteria andPoiOStatusNotIn(List<Integer> values) {
			addCriterion("POI_O_STATUS not in", values, "poiOStatus");
			return (Criteria) this;
		}

		public Criteria andPoiOStatusBetween(Integer value1, Integer value2) {
			addCriterion("POI_O_STATUS between", value1, value2, "poiOStatus");
			return (Criteria) this;
		}

		public Criteria andPoiOStatusNotBetween(Integer value1, Integer value2) {
			addCriterion("POI_O_STATUS not between", value1, value2, "poiOStatus");
			return (Criteria) this;
		}

		public Criteria andPeiOStatusIsNull() {
			addCriterion("PEI_O_STATUS is null");
			return (Criteria) this;
		}

		public Criteria andPeiOStatusIsNotNull() {
			addCriterion("PEI_O_STATUS is not null");
			return (Criteria) this;
		}

		public Criteria andPeiOStatusEqualTo(Integer value) {
			addCriterion("PEI_O_STATUS =", value, "peiOStatus");
			return (Criteria) this;
		}

		public Criteria andPeiOStatusNotEqualTo(Integer value) {
			addCriterion("PEI_O_STATUS <>", value, "peiOStatus");
			return (Criteria) this;
		}

		public Criteria andPeiOStatusGreaterThan(Integer value) {
			addCriterion("PEI_O_STATUS >", value, "peiOStatus");
			return (Criteria) this;
		}

		public Criteria andPeiOStatusGreaterThanOrEqualTo(Integer value) {
			addCriterion("PEI_O_STATUS >=", value, "peiOStatus");
			return (Criteria) this;
		}

		public Criteria andPeiOStatusLessThan(Integer value) {
			addCriterion("PEI_O_STATUS <", value, "peiOStatus");
			return (Criteria) this;
		}

		public Criteria andPeiOStatusLessThanOrEqualTo(Integer value) {
			addCriterion("PEI_O_STATUS <=", value, "peiOStatus");
			return (Criteria) this;
		}

		public Criteria andPeiOStatusIn(List<Integer> values) {
			addCriterion("PEI_O_STATUS in", values, "peiOStatus");
			return (Criteria) this;
		}

		public Criteria andPeiOStatusNotIn(List<Integer> values) {
			addCriterion("PEI_O_STATUS not in", values, "peiOStatus");
			return (Criteria) this;
		}

		public Criteria andPeiOStatusBetween(Integer value1, Integer value2) {
			addCriterion("PEI_O_STATUS between", value1, value2, "peiOStatus");
			return (Criteria) this;
		}

		public Criteria andPeiOStatusNotBetween(Integer value1, Integer value2) {
			addCriterion("PEI_O_STATUS not between", value1, value2, "peiOStatus");
			return (Criteria) this;
		}

		public Criteria andPmiOStatusIsNull() {
			addCriterion("PMI_O_STATUS is null");
			return (Criteria) this;
		}

		public Criteria andPmiOStatusIsNotNull() {
			addCriterion("PMI_O_STATUS is not null");
			return (Criteria) this;
		}

		public Criteria andPmiOStatusEqualTo(Integer value) {
			addCriterion("PMI_O_STATUS =", value, "pmiOStatus");
			return (Criteria) this;
		}

		public Criteria andPmiOStatusNotEqualTo(Integer value) {
			addCriterion("PMI_O_STATUS <>", value, "pmiOStatus");
			return (Criteria) this;
		}

		public Criteria andPmiOStatusGreaterThan(Integer value) {
			addCriterion("PMI_O_STATUS >", value, "pmiOStatus");
			return (Criteria) this;
		}

		public Criteria andPmiOStatusGreaterThanOrEqualTo(Integer value) {
			addCriterion("PMI_O_STATUS >=", value, "pmiOStatus");
			return (Criteria) this;
		}

		public Criteria andPmiOStatusLessThan(Integer value) {
			addCriterion("PMI_O_STATUS <", value, "pmiOStatus");
			return (Criteria) this;
		}

		public Criteria andPmiOStatusLessThanOrEqualTo(Integer value) {
			addCriterion("PMI_O_STATUS <=", value, "pmiOStatus");
			return (Criteria) this;
		}

		public Criteria andPmiOStatusIn(List<Integer> values) {
			addCriterion("PMI_O_STATUS in", values, "pmiOStatus");
			return (Criteria) this;
		}

		public Criteria andPmiOStatusNotIn(List<Integer> values) {
			addCriterion("PMI_O_STATUS not in", values, "pmiOStatus");
			return (Criteria) this;
		}

		public Criteria andPmiOStatusBetween(Integer value1, Integer value2) {
			addCriterion("PMI_O_STATUS between", value1, value2, "pmiOStatus");
			return (Criteria) this;
		}

		public Criteria andPmiOStatusNotBetween(Integer value1, Integer value2) {
			addCriterion("PMI_O_STATUS not between", value1, value2, "pmiOStatus");
			return (Criteria) this;
		}

		public Criteria andPeiTimeIsNull() {
			addCriterion("PEI_TIME is null");
			return (Criteria) this;
		}

		public Criteria andPeiTimeIsNotNull() {
			addCriterion("PEI_TIME is not null");
			return (Criteria) this;
		}

		public Criteria andPeiTimeEqualTo(Date value) {
			addCriterionForJDBCDate("PEI_TIME =", value, "peiTime");
			return (Criteria) this;
		}

		public Criteria andPeiTimeNotEqualTo(Date value) {
			addCriterionForJDBCDate("PEI_TIME <>", value, "peiTime");
			return (Criteria) this;
		}

		public Criteria andPeiTimeGreaterThan(Date value) {
			addCriterionForJDBCDate("PEI_TIME >", value, "peiTime");
			return (Criteria) this;
		}

		public Criteria andPeiTimeGreaterThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("PEI_TIME >=", value, "peiTime");
			return (Criteria) this;
		}

		public Criteria andPeiTimeLessThan(Date value) {
			addCriterionForJDBCDate("PEI_TIME <", value, "peiTime");
			return (Criteria) this;
		}

		public Criteria andPeiTimeLessThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("PEI_TIME <=", value, "peiTime");
			return (Criteria) this;
		}

		public Criteria andPeiTimeIn(List<Date> values) {
			addCriterionForJDBCDate("PEI_TIME in", values, "peiTime");
			return (Criteria) this;
		}

		public Criteria andPeiTimeNotIn(List<Date> values) {
			addCriterionForJDBCDate("PEI_TIME not in", values, "peiTime");
			return (Criteria) this;
		}

		public Criteria andPeiTimeBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("PEI_TIME between", value1, value2, "peiTime");
			return (Criteria) this;
		}

		public Criteria andPeiTimeNotBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("PEI_TIME not between", value1, value2, "peiTime");
			return (Criteria) this;
		}

		public Criteria andPoiTimeIsNull() {
			addCriterion("POI_TIME is null");
			return (Criteria) this;
		}

		public Criteria andPoiTimeIsNotNull() {
			addCriterion("POI_TIME is not null");
			return (Criteria) this;
		}

		public Criteria andPoiTimeEqualTo(Date value) {
			addCriterionForJDBCDate("POI_TIME =", value, "poiTime");
			return (Criteria) this;
		}

		public Criteria andPoiTimeNotEqualTo(Date value) {
			addCriterionForJDBCDate("POI_TIME <>", value, "poiTime");
			return (Criteria) this;
		}

		public Criteria andPoiTimeGreaterThan(Date value) {
			addCriterionForJDBCDate("POI_TIME >", value, "poiTime");
			return (Criteria) this;
		}

		public Criteria andPoiTimeGreaterThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("POI_TIME >=", value, "poiTime");
			return (Criteria) this;
		}

		public Criteria andPoiTimeLessThan(Date value) {
			addCriterionForJDBCDate("POI_TIME <", value, "poiTime");
			return (Criteria) this;
		}

		public Criteria andPoiTimeLessThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("POI_TIME <=", value, "poiTime");
			return (Criteria) this;
		}

		public Criteria andPoiTimeIn(List<Date> values) {
			addCriterionForJDBCDate("POI_TIME in", values, "poiTime");
			return (Criteria) this;
		}

		public Criteria andPoiTimeNotIn(List<Date> values) {
			addCriterionForJDBCDate("POI_TIME not in", values, "poiTime");
			return (Criteria) this;
		}

		public Criteria andPoiTimeBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("POI_TIME between", value1, value2, "poiTime");
			return (Criteria) this;
		}

		public Criteria andPoiTimeNotBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("POI_TIME not between", value1, value2, "poiTime");
			return (Criteria) this;
		}

		public Criteria andPmiTimeIsNull() {
			addCriterion("PMI_TIME is null");
			return (Criteria) this;
		}

		public Criteria andPmiTimeIsNotNull() {
			addCriterion("PMI_TIME is not null");
			return (Criteria) this;
		}

		public Criteria andPmiTimeEqualTo(Date value) {
			addCriterionForJDBCDate("PMI_TIME =", value, "pmiTime");
			return (Criteria) this;
		}

		public Criteria andPmiTimeNotEqualTo(Date value) {
			addCriterionForJDBCDate("PMI_TIME <>", value, "pmiTime");
			return (Criteria) this;
		}

		public Criteria andPmiTimeGreaterThan(Date value) {
			addCriterionForJDBCDate("PMI_TIME >", value, "pmiTime");
			return (Criteria) this;
		}

		public Criteria andPmiTimeGreaterThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("PMI_TIME >=", value, "pmiTime");
			return (Criteria) this;
		}

		public Criteria andPmiTimeLessThan(Date value) {
			addCriterionForJDBCDate("PMI_TIME <", value, "pmiTime");
			return (Criteria) this;
		}

		public Criteria andPmiTimeLessThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("PMI_TIME <=", value, "pmiTime");
			return (Criteria) this;
		}

		public Criteria andPmiTimeIn(List<Date> values) {
			addCriterionForJDBCDate("PMI_TIME in", values, "pmiTime");
			return (Criteria) this;
		}

		public Criteria andPmiTimeNotIn(List<Date> values) {
			addCriterionForJDBCDate("PMI_TIME not in", values, "pmiTime");
			return (Criteria) this;
		}

		public Criteria andPmiTimeBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("PMI_TIME between", value1, value2, "pmiTime");
			return (Criteria) this;
		}

		public Criteria andPmiTimeNotBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("PMI_TIME not between", value1, value2, "pmiTime");
			return (Criteria) this;
		}

		public Criteria andPsiOStatusIsNull() {
			addCriterion("PSI_O_STATUS is null");
			return (Criteria) this;
		}

		public Criteria andPsiOStatusIsNotNull() {
			addCriterion("PSI_O_STATUS is not null");
			return (Criteria) this;
		}

		public Criteria andPsiOStatusEqualTo(Integer value) {
			addCriterion("PSI_O_STATUS =", value, "psiOStatus");
			return (Criteria) this;
		}

		public Criteria andPsiOStatusNotEqualTo(Integer value) {
			addCriterion("PSI_O_STATUS <>", value, "psiOStatus");
			return (Criteria) this;
		}

		public Criteria andPsiOStatusGreaterThan(Integer value) {
			addCriterion("PSI_O_STATUS >", value, "psiOStatus");
			return (Criteria) this;
		}

		public Criteria andPsiOStatusGreaterThanOrEqualTo(Integer value) {
			addCriterion("PSI_O_STATUS >=", value, "psiOStatus");
			return (Criteria) this;
		}

		public Criteria andPsiOStatusLessThan(Integer value) {
			addCriterion("PSI_O_STATUS <", value, "psiOStatus");
			return (Criteria) this;
		}

		public Criteria andPsiOStatusLessThanOrEqualTo(Integer value) {
			addCriterion("PSI_O_STATUS <=", value, "psiOStatus");
			return (Criteria) this;
		}

		public Criteria andPsiOStatusIn(List<Integer> values) {
			addCriterion("PSI_O_STATUS in", values, "psiOStatus");
			return (Criteria) this;
		}

		public Criteria andPsiOStatusNotIn(List<Integer> values) {
			addCriterion("PSI_O_STATUS not in", values, "psiOStatus");
			return (Criteria) this;
		}

		public Criteria andPsiOStatusBetween(Integer value1, Integer value2) {
			addCriterion("PSI_O_STATUS between", value1, value2, "psiOStatus");
			return (Criteria) this;
		}

		public Criteria andPsiOStatusNotBetween(Integer value1, Integer value2) {
			addCriterion("PSI_O_STATUS not between", value1, value2, "psiOStatus");
			return (Criteria) this;
		}

		public Criteria andPbStatusIsNull() {
			addCriterion("PB_STATUS is null");
			return (Criteria) this;
		}

		public Criteria andPbStatusIsNotNull() {
			addCriterion("PB_STATUS is not null");
			return (Criteria) this;
		}

		public Criteria andPbStatusEqualTo(Integer value) {
			addCriterion("PB_STATUS =", value, "pbStatus");
			return (Criteria) this;
		}

		public Criteria andPbStatusNotEqualTo(Integer value) {
			addCriterion("PB_STATUS <>", value, "pbStatus");
			return (Criteria) this;
		}

		public Criteria andPbStatusGreaterThan(Integer value) {
			addCriterion("PB_STATUS >", value, "pbStatus");
			return (Criteria) this;
		}

		public Criteria andPbStatusGreaterThanOrEqualTo(Integer value) {
			addCriterion("PB_STATUS >=", value, "pbStatus");
			return (Criteria) this;
		}

		public Criteria andPbStatusLessThan(Integer value) {
			addCriterion("PB_STATUS <", value, "pbStatus");
			return (Criteria) this;
		}

		public Criteria andPbStatusLessThanOrEqualTo(Integer value) {
			addCriterion("PB_STATUS <=", value, "pbStatus");
			return (Criteria) this;
		}

		public Criteria andPbStatusIn(List<Integer> values) {
			addCriterion("PB_STATUS in", values, "pbStatus");
			return (Criteria) this;
		}

		public Criteria andPbStatusNotIn(List<Integer> values) {
			addCriterion("PB_STATUS not in", values, "pbStatus");
			return (Criteria) this;
		}

		public Criteria andPbStatusBetween(Integer value1, Integer value2) {
			addCriterion("PB_STATUS between", value1, value2, "pbStatus");
			return (Criteria) this;
		}

		public Criteria andPbStatusNotBetween(Integer value1, Integer value2) {
			addCriterion("PB_STATUS not between", value1, value2, "pbStatus");
			return (Criteria) this;
		}

		public Criteria andFStatusIsNull() {
			addCriterion("F_STATUS is null");
			return (Criteria) this;
		}

		public Criteria andFStatusIsNotNull() {
			addCriterion("F_STATUS is not null");
			return (Criteria) this;
		}

		public Criteria andFStatusEqualTo(Integer value) {
			addCriterion("F_STATUS =", value, "fStatus");
			return (Criteria) this;
		}

		public Criteria andFStatusNotEqualTo(Integer value) {
			addCriterion("F_STATUS <>", value, "fStatus");
			return (Criteria) this;
		}

		public Criteria andFStatusGreaterThan(Integer value) {
			addCriterion("F_STATUS >", value, "fStatus");
			return (Criteria) this;
		}

		public Criteria andFStatusGreaterThanOrEqualTo(Integer value) {
			addCriterion("F_STATUS >=", value, "fStatus");
			return (Criteria) this;
		}

		public Criteria andFStatusLessThan(Integer value) {
			addCriterion("F_STATUS <", value, "fStatus");
			return (Criteria) this;
		}

		public Criteria andFStatusLessThanOrEqualTo(Integer value) {
			addCriterion("F_STATUS <=", value, "fStatus");
			return (Criteria) this;
		}

		public Criteria andFStatusIn(List<Integer> values) {
			addCriterion("F_STATUS in", values, "fStatus");
			return (Criteria) this;
		}

		public Criteria andFStatusNotIn(List<Integer> values) {
			addCriterion("F_STATUS not in", values, "fStatus");
			return (Criteria) this;
		}

		public Criteria andFStatusBetween(Integer value1, Integer value2) {
			addCriterion("F_STATUS between", value1, value2, "fStatus");
			return (Criteria) this;
		}

		public Criteria andFStatusNotBetween(Integer value1, Integer value2) {
			addCriterion("F_STATUS not between", value1, value2, "fStatus");
			return (Criteria) this;
		}

		public Criteria andWsStatusIsNull() {
			addCriterion("WS_STATUS is null");
			return (Criteria) this;
		}

		public Criteria andWsStatusIsNotNull() {
			addCriterion("WS_STATUS is not null");
			return (Criteria) this;
		}

		public Criteria andWsStatusEqualTo(Integer value) {
			addCriterion("WS_STATUS =", value, "wsStatus");
			return (Criteria) this;
		}

		public Criteria andWsStatusNotEqualTo(Integer value) {
			addCriterion("WS_STATUS <>", value, "wsStatus");
			return (Criteria) this;
		}

		public Criteria andWsStatusGreaterThan(Integer value) {
			addCriterion("WS_STATUS >", value, "wsStatus");
			return (Criteria) this;
		}

		public Criteria andWsStatusGreaterThanOrEqualTo(Integer value) {
			addCriterion("WS_STATUS >=", value, "wsStatus");
			return (Criteria) this;
		}

		public Criteria andWsStatusLessThan(Integer value) {
			addCriterion("WS_STATUS <", value, "wsStatus");
			return (Criteria) this;
		}

		public Criteria andWsStatusLessThanOrEqualTo(Integer value) {
			addCriterion("WS_STATUS <=", value, "wsStatus");
			return (Criteria) this;
		}

		public Criteria andWsStatusIn(List<Integer> values) {
			addCriterion("WS_STATUS in", values, "wsStatus");
			return (Criteria) this;
		}

		public Criteria andWsStatusNotIn(List<Integer> values) {
			addCriterion("WS_STATUS not in", values, "wsStatus");
			return (Criteria) this;
		}

		public Criteria andWsStatusBetween(Integer value1, Integer value2) {
			addCriterion("WS_STATUS between", value1, value2, "wsStatus");
			return (Criteria) this;
		}

		public Criteria andWsStatusNotBetween(Integer value1, Integer value2) {
			addCriterion("WS_STATUS not between", value1, value2, "wsStatus");
			return (Criteria) this;
		}

		public Criteria andUTypeIsNull() {
			addCriterion("U_TYPE is null");
			return (Criteria) this;
		}

		public Criteria andUTypeIsNotNull() {
			addCriterion("U_TYPE is not null");
			return (Criteria) this;
		}

		public Criteria andUTypeEqualTo(Integer value) {
			addCriterion("U_TYPE =", value, "uType");
			return (Criteria) this;
		}

		public Criteria andUTypeNotEqualTo(Integer value) {
			addCriterion("U_TYPE <>", value, "uType");
			return (Criteria) this;
		}

		public Criteria andUTypeGreaterThan(Integer value) {
			addCriterion("U_TYPE >", value, "uType");
			return (Criteria) this;
		}

		public Criteria andUTypeGreaterThanOrEqualTo(Integer value) {
			addCriterion("U_TYPE >=", value, "uType");
			return (Criteria) this;
		}

		public Criteria andUTypeLessThan(Integer value) {
			addCriterion("U_TYPE <", value, "uType");
			return (Criteria) this;
		}

		public Criteria andUTypeLessThanOrEqualTo(Integer value) {
			addCriterion("U_TYPE <=", value, "uType");
			return (Criteria) this;
		}

		public Criteria andUTypeIn(List<Integer> values) {
			addCriterion("U_TYPE in", values, "uType");
			return (Criteria) this;
		}

		public Criteria andUTypeNotIn(List<Integer> values) {
			addCriterion("U_TYPE not in", values, "uType");
			return (Criteria) this;
		}

		public Criteria andUTypeBetween(Integer value1, Integer value2) {
			addCriterion("U_TYPE between", value1, value2, "uType");
			return (Criteria) this;
		}

		public Criteria andUTypeNotBetween(Integer value1, Integer value2) {
			addCriterion("U_TYPE not between", value1, value2, "uType");
			return (Criteria) this;
		}

		public Criteria andEmailIsNull() {
			addCriterion("Email is null");
			return (Criteria) this;
		}

		public Criteria andEmailIsNotNull() {
			addCriterion("Email is not null");
			return (Criteria) this;
		}

		public Criteria andEmailEqualTo(String value) {
			addCriterion("Email =", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailNotEqualTo(String value) {
			addCriterion("Email <>", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailGreaterThan(String value) {
			addCriterion("Email >", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailGreaterThanOrEqualTo(String value) {
			addCriterion("Email >=", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailLessThan(String value) {
			addCriterion("Email <", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailLessThanOrEqualTo(String value) {
			addCriterion("Email <=", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailLike(String value) {
			addCriterion("Email like", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailNotLike(String value) {
			addCriterion("Email not like", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailIn(List<String> values) {
			addCriterion("Email in", values, "email");
			return (Criteria) this;
		}

		public Criteria andEmailNotIn(List<String> values) {
			addCriterion("Email not in", values, "email");
			return (Criteria) this;
		}

		public Criteria andEmailBetween(String value1, String value2) {
			addCriterion("Email between", value1, value2, "email");
			return (Criteria) this;
		}

		public Criteria andEmailNotBetween(String value1, String value2) {
			addCriterion("Email not between", value1, value2, "email");
			return (Criteria) this;
		}

		public Criteria andGenderIsNull() {
			addCriterion("GENDER is null");
			return (Criteria) this;
		}

		public Criteria andGenderIsNotNull() {
			addCriterion("GENDER is not null");
			return (Criteria) this;
		}

		public Criteria andGenderEqualTo(Integer value) {
			addCriterion("GENDER =", value, "gender");
			return (Criteria) this;
		}

		public Criteria andGenderNotEqualTo(Integer value) {
			addCriterion("GENDER <>", value, "gender");
			return (Criteria) this;
		}

		public Criteria andGenderGreaterThan(Integer value) {
			addCriterion("GENDER >", value, "gender");
			return (Criteria) this;
		}

		public Criteria andGenderGreaterThanOrEqualTo(Integer value) {
			addCriterion("GENDER >=", value, "gender");
			return (Criteria) this;
		}

		public Criteria andGenderLessThan(Integer value) {
			addCriterion("GENDER <", value, "gender");
			return (Criteria) this;
		}

		public Criteria andGenderLessThanOrEqualTo(Integer value) {
			addCriterion("GENDER <=", value, "gender");
			return (Criteria) this;
		}

		public Criteria andGenderIn(List<Integer> values) {
			addCriterion("GENDER in", values, "gender");
			return (Criteria) this;
		}

		public Criteria andGenderNotIn(List<Integer> values) {
			addCriterion("GENDER not in", values, "gender");
			return (Criteria) this;
		}

		public Criteria andGenderBetween(Integer value1, Integer value2) {
			addCriterion("GENDER between", value1, value2, "gender");
			return (Criteria) this;
		}

		public Criteria andGenderNotBetween(Integer value1, Integer value2) {
			addCriterion("GENDER not between", value1, value2, "gender");
			return (Criteria) this;
		}

		public Criteria andCollegeIsNull() {
			addCriterion("COLLEGE is null");
			return (Criteria) this;
		}

		public Criteria andCollegeIsNotNull() {
			addCriterion("COLLEGE is not null");
			return (Criteria) this;
		}

		public Criteria andCollegeEqualTo(String value) {
			addCriterion("COLLEGE =", value, "college");
			return (Criteria) this;
		}

		public Criteria andCollegeNotEqualTo(String value) {
			addCriterion("COLLEGE <>", value, "college");
			return (Criteria) this;
		}

		public Criteria andCollegeGreaterThan(String value) {
			addCriterion("COLLEGE >", value, "college");
			return (Criteria) this;
		}

		public Criteria andCollegeGreaterThanOrEqualTo(String value) {
			addCriterion("COLLEGE >=", value, "college");
			return (Criteria) this;
		}

		public Criteria andCollegeLessThan(String value) {
			addCriterion("COLLEGE <", value, "college");
			return (Criteria) this;
		}

		public Criteria andCollegeLessThanOrEqualTo(String value) {
			addCriterion("COLLEGE <=", value, "college");
			return (Criteria) this;
		}

		public Criteria andCollegeLike(String value) {
			addCriterion("COLLEGE like", value, "college");
			return (Criteria) this;
		}

		public Criteria andCollegeNotLike(String value) {
			addCriterion("COLLEGE not like", value, "college");
			return (Criteria) this;
		}

		public Criteria andCollegeIn(List<String> values) {
			addCriterion("COLLEGE in", values, "college");
			return (Criteria) this;
		}

		public Criteria andCollegeNotIn(List<String> values) {
			addCriterion("COLLEGE not in", values, "college");
			return (Criteria) this;
		}

		public Criteria andCollegeBetween(String value1, String value2) {
			addCriterion("COLLEGE between", value1, value2, "college");
			return (Criteria) this;
		}

		public Criteria andCollegeNotBetween(String value1, String value2) {
			addCriterion("COLLEGE not between", value1, value2, "college");
			return (Criteria) this;
		}

		public Criteria andMajorIsNull() {
			addCriterion("MAJOR is null");
			return (Criteria) this;
		}

		public Criteria andMajorIsNotNull() {
			addCriterion("MAJOR is not null");
			return (Criteria) this;
		}

		public Criteria andMajorEqualTo(String value) {
			addCriterion("MAJOR =", value, "major");
			return (Criteria) this;
		}

		public Criteria andMajorNotEqualTo(String value) {
			addCriterion("MAJOR <>", value, "major");
			return (Criteria) this;
		}

		public Criteria andMajorGreaterThan(String value) {
			addCriterion("MAJOR >", value, "major");
			return (Criteria) this;
		}

		public Criteria andMajorGreaterThanOrEqualTo(String value) {
			addCriterion("MAJOR >=", value, "major");
			return (Criteria) this;
		}

		public Criteria andMajorLessThan(String value) {
			addCriterion("MAJOR <", value, "major");
			return (Criteria) this;
		}

		public Criteria andMajorLessThanOrEqualTo(String value) {
			addCriterion("MAJOR <=", value, "major");
			return (Criteria) this;
		}

		public Criteria andMajorLike(String value) {
			addCriterion("MAJOR like", value, "major");
			return (Criteria) this;
		}

		public Criteria andMajorNotLike(String value) {
			addCriterion("MAJOR not like", value, "major");
			return (Criteria) this;
		}

		public Criteria andMajorIn(List<String> values) {
			addCriterion("MAJOR in", values, "major");
			return (Criteria) this;
		}

		public Criteria andMajorNotIn(List<String> values) {
			addCriterion("MAJOR not in", values, "major");
			return (Criteria) this;
		}

		public Criteria andMajorBetween(String value1, String value2) {
			addCriterion("MAJOR between", value1, value2, "major");
			return (Criteria) this;
		}

		public Criteria andMajorNotBetween(String value1, String value2) {
			addCriterion("MAJOR not between", value1, value2, "major");
			return (Criteria) this;
		}

		public Criteria andTelIsNull() {
			addCriterion("TEL is null");
			return (Criteria) this;
		}

		public Criteria andTelIsNotNull() {
			addCriterion("TEL is not null");
			return (Criteria) this;
		}

		public Criteria andTelEqualTo(String value) {
			addCriterion("TEL =", value, "tel");
			return (Criteria) this;
		}

		public Criteria andTelNotEqualTo(String value) {
			addCriterion("TEL <>", value, "tel");
			return (Criteria) this;
		}

		public Criteria andTelGreaterThan(String value) {
			addCriterion("TEL >", value, "tel");
			return (Criteria) this;
		}

		public Criteria andTelGreaterThanOrEqualTo(String value) {
			addCriterion("TEL >=", value, "tel");
			return (Criteria) this;
		}

		public Criteria andTelLessThan(String value) {
			addCriterion("TEL <", value, "tel");
			return (Criteria) this;
		}

		public Criteria andTelLessThanOrEqualTo(String value) {
			addCriterion("TEL <=", value, "tel");
			return (Criteria) this;
		}

		public Criteria andTelLike(String value) {
			addCriterion("TEL like", value, "tel");
			return (Criteria) this;
		}

		public Criteria andTelNotLike(String value) {
			addCriterion("TEL not like", value, "tel");
			return (Criteria) this;
		}

		public Criteria andTelIn(List<String> values) {
			addCriterion("TEL in", values, "tel");
			return (Criteria) this;
		}

		public Criteria andTelNotIn(List<String> values) {
			addCriterion("TEL not in", values, "tel");
			return (Criteria) this;
		}

		public Criteria andTelBetween(String value1, String value2) {
			addCriterion("TEL between", value1, value2, "tel");
			return (Criteria) this;
		}

		public Criteria andTelNotBetween(String value1, String value2) {
			addCriterion("TEL not between", value1, value2, "tel");
			return (Criteria) this;
		}

		public Criteria andAdmissionDateIsNull() {
			addCriterion("ADMISSION_DATE is null");
			return (Criteria) this;
		}

		public Criteria andAdmissionDateIsNotNull() {
			addCriterion("ADMISSION_DATE is not null");
			return (Criteria) this;
		}

		public Criteria andAdmissionDateEqualTo(Date value) {
			addCriterionForJDBCDate("ADMISSION_DATE =", value, "admissionDate");
			return (Criteria) this;
		}

		public Criteria andAdmissionDateNotEqualTo(Date value) {
			addCriterionForJDBCDate("ADMISSION_DATE <>", value, "admissionDate");
			return (Criteria) this;
		}

		public Criteria andAdmissionDateGreaterThan(Date value) {
			addCriterionForJDBCDate("ADMISSION_DATE >", value, "admissionDate");
			return (Criteria) this;
		}

		public Criteria andAdmissionDateGreaterThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("ADMISSION_DATE >=", value, "admissionDate");
			return (Criteria) this;
		}

		public Criteria andAdmissionDateLessThan(Date value) {
			addCriterionForJDBCDate("ADMISSION_DATE <", value, "admissionDate");
			return (Criteria) this;
		}

		public Criteria andAdmissionDateLessThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("ADMISSION_DATE <=", value, "admissionDate");
			return (Criteria) this;
		}

		public Criteria andAdmissionDateIn(List<Date> values) {
			addCriterionForJDBCDate("ADMISSION_DATE in", values, "admissionDate");
			return (Criteria) this;
		}

		public Criteria andAdmissionDateNotIn(List<Date> values) {
			addCriterionForJDBCDate("ADMISSION_DATE not in", values, "admissionDate");
			return (Criteria) this;
		}

		public Criteria andAdmissionDateBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("ADMISSION_DATE between", value1, value2, "admissionDate");
			return (Criteria) this;
		}

		public Criteria andAdmissionDateNotBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("ADMISSION_DATE not between", value1, value2, "admissionDate");
			return (Criteria) this;
		}

		public Criteria andJobTitleIsNull() {
			addCriterion("JOB_TITLE is null");
			return (Criteria) this;
		}

		public Criteria andJobTitleIsNotNull() {
			addCriterion("JOB_TITLE is not null");
			return (Criteria) this;
		}

		public Criteria andJobTitleEqualTo(String value) {
			addCriterion("JOB_TITLE =", value, "jobTitle");
			return (Criteria) this;
		}

		public Criteria andJobTitleNotEqualTo(String value) {
			addCriterion("JOB_TITLE <>", value, "jobTitle");
			return (Criteria) this;
		}

		public Criteria andJobTitleGreaterThan(String value) {
			addCriterion("JOB_TITLE >", value, "jobTitle");
			return (Criteria) this;
		}

		public Criteria andJobTitleGreaterThanOrEqualTo(String value) {
			addCriterion("JOB_TITLE >=", value, "jobTitle");
			return (Criteria) this;
		}

		public Criteria andJobTitleLessThan(String value) {
			addCriterion("JOB_TITLE <", value, "jobTitle");
			return (Criteria) this;
		}

		public Criteria andJobTitleLessThanOrEqualTo(String value) {
			addCriterion("JOB_TITLE <=", value, "jobTitle");
			return (Criteria) this;
		}

		public Criteria andJobTitleLike(String value) {
			addCriterion("JOB_TITLE like", value, "jobTitle");
			return (Criteria) this;
		}

		public Criteria andJobTitleNotLike(String value) {
			addCriterion("JOB_TITLE not like", value, "jobTitle");
			return (Criteria) this;
		}

		public Criteria andJobTitleIn(List<String> values) {
			addCriterion("JOB_TITLE in", values, "jobTitle");
			return (Criteria) this;
		}

		public Criteria andJobTitleNotIn(List<String> values) {
			addCriterion("JOB_TITLE not in", values, "jobTitle");
			return (Criteria) this;
		}

		public Criteria andJobTitleBetween(String value1, String value2) {
			addCriterion("JOB_TITLE between", value1, value2, "jobTitle");
			return (Criteria) this;
		}

		public Criteria andJobTitleNotBetween(String value1, String value2) {
			addCriterion("JOB_TITLE not between", value1, value2, "jobTitle");
			return (Criteria) this;
		}

		public Criteria andRoleIsNull() {
			addCriterion("ROLE is null");
			return (Criteria) this;
		}

		public Criteria andRoleIsNotNull() {
			addCriterion("ROLE is not null");
			return (Criteria) this;
		}

		public Criteria andRoleEqualTo(Integer value) {
			addCriterion("ROLE =", value, "role");
			return (Criteria) this;
		}

		public Criteria andRoleNotEqualTo(Integer value) {
			addCriterion("ROLE <>", value, "role");
			return (Criteria) this;
		}

		public Criteria andRoleGreaterThan(Integer value) {
			addCriterion("ROLE >", value, "role");
			return (Criteria) this;
		}

		public Criteria andRoleGreaterThanOrEqualTo(Integer value) {
			addCriterion("ROLE >=", value, "role");
			return (Criteria) this;
		}

		public Criteria andRoleLessThan(Integer value) {
			addCriterion("ROLE <", value, "role");
			return (Criteria) this;
		}

		public Criteria andRoleLessThanOrEqualTo(Integer value) {
			addCriterion("ROLE <=", value, "role");
			return (Criteria) this;
		}

		public Criteria andRoleIn(List<Integer> values) {
			addCriterion("ROLE in", values, "role");
			return (Criteria) this;
		}

		public Criteria andRoleNotIn(List<Integer> values) {
			addCriterion("ROLE not in", values, "role");
			return (Criteria) this;
		}

		public Criteria andRoleBetween(Integer value1, Integer value2) {
			addCriterion("ROLE between", value1, value2, "role");
			return (Criteria) this;
		}

		public Criteria andRoleNotBetween(Integer value1, Integer value2) {
			addCriterion("ROLE not between", value1, value2, "role");
			return (Criteria) this;
		}

		public Criteria andUCodeIsNull() {
			addCriterion("U_CODE is null");
			return (Criteria) this;
		}

		public Criteria andUCodeIsNotNull() {
			addCriterion("U_CODE is not null");
			return (Criteria) this;
		}

		public Criteria andUCodeEqualTo(String value) {
			addCriterion("U_CODE =", value, "uCode");
			return (Criteria) this;
		}

		public Criteria andUCodeNotEqualTo(String value) {
			addCriterion("U_CODE <>", value, "uCode");
			return (Criteria) this;
		}

		public Criteria andUCodeGreaterThan(String value) {
			addCriterion("U_CODE >", value, "uCode");
			return (Criteria) this;
		}

		public Criteria andUCodeGreaterThanOrEqualTo(String value) {
			addCriterion("U_CODE >=", value, "uCode");
			return (Criteria) this;
		}

		public Criteria andUCodeLessThan(String value) {
			addCriterion("U_CODE <", value, "uCode");
			return (Criteria) this;
		}

		public Criteria andUCodeLessThanOrEqualTo(String value) {
			addCriterion("U_CODE <=", value, "uCode");
			return (Criteria) this;
		}

		public Criteria andUCodeLike(String value) {
			addCriterion("U_CODE like", value, "uCode");
			return (Criteria) this;
		}

		public Criteria andUCodeNotLike(String value) {
			addCriterion("U_CODE not like", value, "uCode");
			return (Criteria) this;
		}

		public Criteria andUCodeIn(List<String> values) {
			addCriterion("U_CODE in", values, "uCode");
			return (Criteria) this;
		}

		public Criteria andUCodeNotIn(List<String> values) {
			addCriterion("U_CODE not in", values, "uCode");
			return (Criteria) this;
		}

		public Criteria andUCodeBetween(String value1, String value2) {
			addCriterion("U_CODE between", value1, value2, "uCode");
			return (Criteria) this;
		}

		public Criteria andUCodeNotBetween(String value1, String value2) {
			addCriterion("U_CODE not between", value1, value2, "uCode");
			return (Criteria) this;
		}

		public Criteria andPuIdIsNull() {
			addCriterion("PU_ID is null");
			return (Criteria) this;
		}

		public Criteria andPuIdIsNotNull() {
			addCriterion("PU_ID is not null");
			return (Criteria) this;
		}

		public Criteria andPuIdEqualTo(Integer value) {
			addCriterion("PU_ID =", value, "puId");
			return (Criteria) this;
		}

		public Criteria andPuIdNotEqualTo(Integer value) {
			addCriterion("PU_ID <>", value, "puId");
			return (Criteria) this;
		}

		public Criteria andPuIdGreaterThan(Integer value) {
			addCriterion("PU_ID >", value, "puId");
			return (Criteria) this;
		}

		public Criteria andPuIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("PU_ID >=", value, "puId");
			return (Criteria) this;
		}

		public Criteria andPuIdLessThan(Integer value) {
			addCriterion("PU_ID <", value, "puId");
			return (Criteria) this;
		}

		public Criteria andPuIdLessThanOrEqualTo(Integer value) {
			addCriterion("PU_ID <=", value, "puId");
			return (Criteria) this;
		}

		public Criteria andPuIdIn(List<Integer> values) {
			addCriterion("PU_ID in", values, "puId");
			return (Criteria) this;
		}

		public Criteria andPuIdNotIn(List<Integer> values) {
			addCriterion("PU_ID not in", values, "puId");
			return (Criteria) this;
		}

		public Criteria andPuIdBetween(Integer value1, Integer value2) {
			addCriterion("PU_ID between", value1, value2, "puId");
			return (Criteria) this;
		}

		public Criteria andPuIdNotBetween(Integer value1, Integer value2) {
			addCriterion("PU_ID not between", value1, value2, "puId");
			return (Criteria) this;
		}

		public Criteria andPpIdIsNull() {
			addCriterion("PP_ID is null");
			return (Criteria) this;
		}

		public Criteria andPpIdIsNotNull() {
			addCriterion("PP_ID is not null");
			return (Criteria) this;
		}

		public Criteria andPpIdEqualTo(Integer value) {
			addCriterion("PP_ID =", value, "ppId");
			return (Criteria) this;
		}

		public Criteria andPpIdNotEqualTo(Integer value) {
			addCriterion("PP_ID <>", value, "ppId");
			return (Criteria) this;
		}

		public Criteria andPpIdGreaterThan(Integer value) {
			addCriterion("PP_ID >", value, "ppId");
			return (Criteria) this;
		}

		public Criteria andPpIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("PP_ID >=", value, "ppId");
			return (Criteria) this;
		}

		public Criteria andPpIdLessThan(Integer value) {
			addCriterion("PP_ID <", value, "ppId");
			return (Criteria) this;
		}

		public Criteria andPpIdLessThanOrEqualTo(Integer value) {
			addCriterion("PP_ID <=", value, "ppId");
			return (Criteria) this;
		}

		public Criteria andPpIdIn(List<Integer> values) {
			addCriterion("PP_ID in", values, "ppId");
			return (Criteria) this;
		}

		public Criteria andPpIdNotIn(List<Integer> values) {
			addCriterion("PP_ID not in", values, "ppId");
			return (Criteria) this;
		}

		public Criteria andPpIdBetween(Integer value1, Integer value2) {
			addCriterion("PP_ID between", value1, value2, "ppId");
			return (Criteria) this;
		}

		public Criteria andPpIdNotBetween(Integer value1, Integer value2) {
			addCriterion("PP_ID not between", value1, value2, "ppId");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table project_base_view
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table project_base_view
     *
     * @mbg.generated do_not_delete_during_merge Sun May 06 20:50:13 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}