package com.plm.model;

public class ProjectUser {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column project_user.PU_ID
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	private Integer puId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column project_user.U_ID
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	private Integer uId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column project_user.PB_ID
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	private Integer pbId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column project_user.U_TYPE
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	private Integer uType;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column project_user.PU_ID
	 * @return  the value of project_user.PU_ID
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public Integer getPuId() {
		return puId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column project_user.PU_ID
	 * @param puId  the value for project_user.PU_ID
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public void setPuId(Integer puId) {
		this.puId = puId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column project_user.U_ID
	 * @return  the value of project_user.U_ID
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public Integer getuId() {
		return uId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column project_user.U_ID
	 * @param uId  the value for project_user.U_ID
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public void setuId(Integer uId) {
		this.uId = uId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column project_user.PB_ID
	 * @return  the value of project_user.PB_ID
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public Integer getPbId() {
		return pbId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column project_user.PB_ID
	 * @param pbId  the value for project_user.PB_ID
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public void setPbId(Integer pbId) {
		this.pbId = pbId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column project_user.U_TYPE
	 * @return  the value of project_user.U_TYPE
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public Integer getuType() {
		return uType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column project_user.U_TYPE
	 * @param uType  the value for project_user.U_TYPE
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public void setuType(Integer uType) {
		this.uType = uType;
	}
}