package com.plm.model;

import java.util.Date;

public class ProjectBaseView {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column project_base_view.PB_ID
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	private Integer pbId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column project_base_view.U_ID
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	private Integer uId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column project_base_view.U_NAME
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	private String uName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column project_base_view.U_REALNAME
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	private String uRealname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column project_base_view.PB_CREATE_TIME
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	private Date pbCreateTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column project_base_view.PB_EDIT_TIME
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	private Date pbEditTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column project_base_view.PB_NAME
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	private String pbName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column project_base_view.PB_LEVEL
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	private Integer pbLevel;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column project_base_view.PB_TYPE
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	private Integer pbType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column project_base_view.SUBJECT_TYPE
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	private Integer subjectType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column project_base_view.PSI_BRIEF
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	private String psiBrief;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column project_base_view.POI_O_STATUS
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	private Integer poiOStatus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column project_base_view.PEI_O_STATUS
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	private Integer peiOStatus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column project_base_view.PMI_O_STATUS
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	private Integer pmiOStatus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column project_base_view.PEI_TIME
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	private Date peiTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column project_base_view.POI_TIME
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	private Date poiTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column project_base_view.PMI_TIME
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	private Date pmiTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column project_base_view.PSI_O_STATUS
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	private Integer psiOStatus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column project_base_view.PB_STATUS
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	private Integer pbStatus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column project_base_view.F_STATUS
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	private Integer fStatus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column project_base_view.WS_STATUS
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	private Integer wsStatus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column project_base_view.U_TYPE
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	private Integer uType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column project_base_view.Email
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	private String email;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column project_base_view.GENDER
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	private Integer gender;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column project_base_view.COLLEGE
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	private String college;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column project_base_view.MAJOR
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	private String major;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column project_base_view.TEL
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	private String tel;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column project_base_view.ADMISSION_DATE
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	private Date admissionDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column project_base_view.JOB_TITLE
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	private String jobTitle;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column project_base_view.ROLE
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	private Integer role;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column project_base_view.U_CODE
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	private String uCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column project_base_view.PU_ID
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	private Integer puId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column project_base_view.PP_ID
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	private Integer ppId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column project_base_view.PB_ID
	 * @return  the value of project_base_view.PB_ID
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public Integer getPbId() {
		return pbId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column project_base_view.PB_ID
	 * @param pbId  the value for project_base_view.PB_ID
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public void setPbId(Integer pbId) {
		this.pbId = pbId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column project_base_view.U_ID
	 * @return  the value of project_base_view.U_ID
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public Integer getuId() {
		return uId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column project_base_view.U_ID
	 * @param uId  the value for project_base_view.U_ID
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public void setuId(Integer uId) {
		this.uId = uId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column project_base_view.U_NAME
	 * @return  the value of project_base_view.U_NAME
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public String getuName() {
		return uName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column project_base_view.U_NAME
	 * @param uName  the value for project_base_view.U_NAME
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public void setuName(String uName) {
		this.uName = uName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column project_base_view.U_REALNAME
	 * @return  the value of project_base_view.U_REALNAME
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public String getuRealname() {
		return uRealname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column project_base_view.U_REALNAME
	 * @param uRealname  the value for project_base_view.U_REALNAME
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public void setuRealname(String uRealname) {
		this.uRealname = uRealname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column project_base_view.PB_CREATE_TIME
	 * @return  the value of project_base_view.PB_CREATE_TIME
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public Date getPbCreateTime() {
		return pbCreateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column project_base_view.PB_CREATE_TIME
	 * @param pbCreateTime  the value for project_base_view.PB_CREATE_TIME
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public void setPbCreateTime(Date pbCreateTime) {
		this.pbCreateTime = pbCreateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column project_base_view.PB_EDIT_TIME
	 * @return  the value of project_base_view.PB_EDIT_TIME
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public Date getPbEditTime() {
		return pbEditTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column project_base_view.PB_EDIT_TIME
	 * @param pbEditTime  the value for project_base_view.PB_EDIT_TIME
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public void setPbEditTime(Date pbEditTime) {
		this.pbEditTime = pbEditTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column project_base_view.PB_NAME
	 * @return  the value of project_base_view.PB_NAME
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public String getPbName() {
		return pbName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column project_base_view.PB_NAME
	 * @param pbName  the value for project_base_view.PB_NAME
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public void setPbName(String pbName) {
		this.pbName = pbName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column project_base_view.PB_LEVEL
	 * @return  the value of project_base_view.PB_LEVEL
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public Integer getPbLevel() {
		return pbLevel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column project_base_view.PB_LEVEL
	 * @param pbLevel  the value for project_base_view.PB_LEVEL
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public void setPbLevel(Integer pbLevel) {
		this.pbLevel = pbLevel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column project_base_view.PB_TYPE
	 * @return  the value of project_base_view.PB_TYPE
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public Integer getPbType() {
		return pbType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column project_base_view.PB_TYPE
	 * @param pbType  the value for project_base_view.PB_TYPE
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public void setPbType(Integer pbType) {
		this.pbType = pbType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column project_base_view.SUBJECT_TYPE
	 * @return  the value of project_base_view.SUBJECT_TYPE
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public Integer getSubjectType() {
		return subjectType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column project_base_view.SUBJECT_TYPE
	 * @param subjectType  the value for project_base_view.SUBJECT_TYPE
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public void setSubjectType(Integer subjectType) {
		this.subjectType = subjectType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column project_base_view.PSI_BRIEF
	 * @return  the value of project_base_view.PSI_BRIEF
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public String getPsiBrief() {
		return psiBrief;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column project_base_view.PSI_BRIEF
	 * @param psiBrief  the value for project_base_view.PSI_BRIEF
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public void setPsiBrief(String psiBrief) {
		this.psiBrief = psiBrief;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column project_base_view.POI_O_STATUS
	 * @return  the value of project_base_view.POI_O_STATUS
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public Integer getPoiOStatus() {
		return poiOStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column project_base_view.POI_O_STATUS
	 * @param poiOStatus  the value for project_base_view.POI_O_STATUS
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public void setPoiOStatus(Integer poiOStatus) {
		this.poiOStatus = poiOStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column project_base_view.PEI_O_STATUS
	 * @return  the value of project_base_view.PEI_O_STATUS
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public Integer getPeiOStatus() {
		return peiOStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column project_base_view.PEI_O_STATUS
	 * @param peiOStatus  the value for project_base_view.PEI_O_STATUS
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public void setPeiOStatus(Integer peiOStatus) {
		this.peiOStatus = peiOStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column project_base_view.PMI_O_STATUS
	 * @return  the value of project_base_view.PMI_O_STATUS
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public Integer getPmiOStatus() {
		return pmiOStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column project_base_view.PMI_O_STATUS
	 * @param pmiOStatus  the value for project_base_view.PMI_O_STATUS
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public void setPmiOStatus(Integer pmiOStatus) {
		this.pmiOStatus = pmiOStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column project_base_view.PEI_TIME
	 * @return  the value of project_base_view.PEI_TIME
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public Date getPeiTime() {
		return peiTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column project_base_view.PEI_TIME
	 * @param peiTime  the value for project_base_view.PEI_TIME
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public void setPeiTime(Date peiTime) {
		this.peiTime = peiTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column project_base_view.POI_TIME
	 * @return  the value of project_base_view.POI_TIME
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public Date getPoiTime() {
		return poiTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column project_base_view.POI_TIME
	 * @param poiTime  the value for project_base_view.POI_TIME
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public void setPoiTime(Date poiTime) {
		this.poiTime = poiTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column project_base_view.PMI_TIME
	 * @return  the value of project_base_view.PMI_TIME
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public Date getPmiTime() {
		return pmiTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column project_base_view.PMI_TIME
	 * @param pmiTime  the value for project_base_view.PMI_TIME
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public void setPmiTime(Date pmiTime) {
		this.pmiTime = pmiTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column project_base_view.PSI_O_STATUS
	 * @return  the value of project_base_view.PSI_O_STATUS
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public Integer getPsiOStatus() {
		return psiOStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column project_base_view.PSI_O_STATUS
	 * @param psiOStatus  the value for project_base_view.PSI_O_STATUS
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public void setPsiOStatus(Integer psiOStatus) {
		this.psiOStatus = psiOStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column project_base_view.PB_STATUS
	 * @return  the value of project_base_view.PB_STATUS
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public Integer getPbStatus() {
		return pbStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column project_base_view.PB_STATUS
	 * @param pbStatus  the value for project_base_view.PB_STATUS
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public void setPbStatus(Integer pbStatus) {
		this.pbStatus = pbStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column project_base_view.F_STATUS
	 * @return  the value of project_base_view.F_STATUS
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public Integer getfStatus() {
		return fStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column project_base_view.F_STATUS
	 * @param fStatus  the value for project_base_view.F_STATUS
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public void setfStatus(Integer fStatus) {
		this.fStatus = fStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column project_base_view.WS_STATUS
	 * @return  the value of project_base_view.WS_STATUS
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public Integer getWsStatus() {
		return wsStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column project_base_view.WS_STATUS
	 * @param wsStatus  the value for project_base_view.WS_STATUS
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public void setWsStatus(Integer wsStatus) {
		this.wsStatus = wsStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column project_base_view.U_TYPE
	 * @return  the value of project_base_view.U_TYPE
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public Integer getuType() {
		return uType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column project_base_view.U_TYPE
	 * @param uType  the value for project_base_view.U_TYPE
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public void setuType(Integer uType) {
		this.uType = uType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column project_base_view.Email
	 * @return  the value of project_base_view.Email
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public String getEmail() {
		return email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column project_base_view.Email
	 * @param email  the value for project_base_view.Email
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public void setEmail(String email) {
		this.email = email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column project_base_view.GENDER
	 * @return  the value of project_base_view.GENDER
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public Integer getGender() {
		return gender;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column project_base_view.GENDER
	 * @param gender  the value for project_base_view.GENDER
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public void setGender(Integer gender) {
		this.gender = gender;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column project_base_view.COLLEGE
	 * @return  the value of project_base_view.COLLEGE
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public String getCollege() {
		return college;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column project_base_view.COLLEGE
	 * @param college  the value for project_base_view.COLLEGE
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public void setCollege(String college) {
		this.college = college;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column project_base_view.MAJOR
	 * @return  the value of project_base_view.MAJOR
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public String getMajor() {
		return major;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column project_base_view.MAJOR
	 * @param major  the value for project_base_view.MAJOR
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public void setMajor(String major) {
		this.major = major;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column project_base_view.TEL
	 * @return  the value of project_base_view.TEL
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public String getTel() {
		return tel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column project_base_view.TEL
	 * @param tel  the value for project_base_view.TEL
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public void setTel(String tel) {
		this.tel = tel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column project_base_view.ADMISSION_DATE
	 * @return  the value of project_base_view.ADMISSION_DATE
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public Date getAdmissionDate() {
		return admissionDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column project_base_view.ADMISSION_DATE
	 * @param admissionDate  the value for project_base_view.ADMISSION_DATE
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public void setAdmissionDate(Date admissionDate) {
		this.admissionDate = admissionDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column project_base_view.JOB_TITLE
	 * @return  the value of project_base_view.JOB_TITLE
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public String getJobTitle() {
		return jobTitle;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column project_base_view.JOB_TITLE
	 * @param jobTitle  the value for project_base_view.JOB_TITLE
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public void setJobTitle(String jobTitle) {
		this.jobTitle = jobTitle;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column project_base_view.ROLE
	 * @return  the value of project_base_view.ROLE
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public Integer getRole() {
		return role;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column project_base_view.ROLE
	 * @param role  the value for project_base_view.ROLE
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public void setRole(Integer role) {
		this.role = role;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column project_base_view.U_CODE
	 * @return  the value of project_base_view.U_CODE
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public String getuCode() {
		return uCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column project_base_view.U_CODE
	 * @param uCode  the value for project_base_view.U_CODE
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public void setuCode(String uCode) {
		this.uCode = uCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column project_base_view.PU_ID
	 * @return  the value of project_base_view.PU_ID
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public Integer getPuId() {
		return puId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column project_base_view.PU_ID
	 * @param puId  the value for project_base_view.PU_ID
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public void setPuId(Integer puId) {
		this.puId = puId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column project_base_view.PP_ID
	 * @return  the value of project_base_view.PP_ID
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public Integer getPpId() {
		return ppId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column project_base_view.PP_ID
	 * @param ppId  the value for project_base_view.PP_ID
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public void setPpId(Integer ppId) {
		this.ppId = ppId;
	}
}