package com.plm.model;

import java.util.Date;

public class ProjectStartView {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column project_start_view.PB_ID
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	private Integer pbId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column project_start_view.PPI_ID
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	private Integer ppiId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column project_start_view.PPI_CREATE_TIME
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	private Date ppiCreateTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column project_start_view.PPI_EDIT_TIME
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	private Date ppiEditTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column project_start_view.PPI_TYPE
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	private Integer ppiType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column project_start_view.PB_CREATE_TIME
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	private Date pbCreateTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column project_start_view.PB_EDIT_TIME
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	private Date pbEditTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column project_start_view.PB_NAME
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	private String pbName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column project_start_view.PB_LEVEL
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	private Integer pbLevel;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column project_start_view.PB_TYPE
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	private Integer pbType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column project_start_view.SUBJECT_TYPE
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	private Integer subjectType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column project_start_view.PSI_BRIEF
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	private String psiBrief;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column project_start_view.PSI_REASON
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	private String psiReason;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column project_start_view.PSI_CONTENT
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	private String psiContent;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column project_start_view.PSI_FEATURE
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	private String psiFeature;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column project_start_view.PSI_PLAN
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	private String psiPlan;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column project_start_view.PSI_RESULT
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	private String psiResult;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column project_start_view.U_ID
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	private Integer uId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column project_start_view.U_TYPE
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	private Integer uType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column project_start_view.PSI_O_STATUS
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	private Integer psiOStatus;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column project_start_view.PB_ID
	 * @return  the value of project_start_view.PB_ID
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public Integer getPbId() {
		return pbId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column project_start_view.PB_ID
	 * @param pbId  the value for project_start_view.PB_ID
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public void setPbId(Integer pbId) {
		this.pbId = pbId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column project_start_view.PPI_ID
	 * @return  the value of project_start_view.PPI_ID
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public Integer getPpiId() {
		return ppiId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column project_start_view.PPI_ID
	 * @param ppiId  the value for project_start_view.PPI_ID
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public void setPpiId(Integer ppiId) {
		this.ppiId = ppiId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column project_start_view.PPI_CREATE_TIME
	 * @return  the value of project_start_view.PPI_CREATE_TIME
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public Date getPpiCreateTime() {
		return ppiCreateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column project_start_view.PPI_CREATE_TIME
	 * @param ppiCreateTime  the value for project_start_view.PPI_CREATE_TIME
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public void setPpiCreateTime(Date ppiCreateTime) {
		this.ppiCreateTime = ppiCreateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column project_start_view.PPI_EDIT_TIME
	 * @return  the value of project_start_view.PPI_EDIT_TIME
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public Date getPpiEditTime() {
		return ppiEditTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column project_start_view.PPI_EDIT_TIME
	 * @param ppiEditTime  the value for project_start_view.PPI_EDIT_TIME
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public void setPpiEditTime(Date ppiEditTime) {
		this.ppiEditTime = ppiEditTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column project_start_view.PPI_TYPE
	 * @return  the value of project_start_view.PPI_TYPE
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public Integer getPpiType() {
		return ppiType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column project_start_view.PPI_TYPE
	 * @param ppiType  the value for project_start_view.PPI_TYPE
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public void setPpiType(Integer ppiType) {
		this.ppiType = ppiType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column project_start_view.PB_CREATE_TIME
	 * @return  the value of project_start_view.PB_CREATE_TIME
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public Date getPbCreateTime() {
		return pbCreateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column project_start_view.PB_CREATE_TIME
	 * @param pbCreateTime  the value for project_start_view.PB_CREATE_TIME
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public void setPbCreateTime(Date pbCreateTime) {
		this.pbCreateTime = pbCreateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column project_start_view.PB_EDIT_TIME
	 * @return  the value of project_start_view.PB_EDIT_TIME
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public Date getPbEditTime() {
		return pbEditTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column project_start_view.PB_EDIT_TIME
	 * @param pbEditTime  the value for project_start_view.PB_EDIT_TIME
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public void setPbEditTime(Date pbEditTime) {
		this.pbEditTime = pbEditTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column project_start_view.PB_NAME
	 * @return  the value of project_start_view.PB_NAME
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public String getPbName() {
		return pbName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column project_start_view.PB_NAME
	 * @param pbName  the value for project_start_view.PB_NAME
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public void setPbName(String pbName) {
		this.pbName = pbName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column project_start_view.PB_LEVEL
	 * @return  the value of project_start_view.PB_LEVEL
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public Integer getPbLevel() {
		return pbLevel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column project_start_view.PB_LEVEL
	 * @param pbLevel  the value for project_start_view.PB_LEVEL
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public void setPbLevel(Integer pbLevel) {
		this.pbLevel = pbLevel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column project_start_view.PB_TYPE
	 * @return  the value of project_start_view.PB_TYPE
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public Integer getPbType() {
		return pbType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column project_start_view.PB_TYPE
	 * @param pbType  the value for project_start_view.PB_TYPE
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public void setPbType(Integer pbType) {
		this.pbType = pbType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column project_start_view.SUBJECT_TYPE
	 * @return  the value of project_start_view.SUBJECT_TYPE
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public Integer getSubjectType() {
		return subjectType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column project_start_view.SUBJECT_TYPE
	 * @param subjectType  the value for project_start_view.SUBJECT_TYPE
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public void setSubjectType(Integer subjectType) {
		this.subjectType = subjectType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column project_start_view.PSI_BRIEF
	 * @return  the value of project_start_view.PSI_BRIEF
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public String getPsiBrief() {
		return psiBrief;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column project_start_view.PSI_BRIEF
	 * @param psiBrief  the value for project_start_view.PSI_BRIEF
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public void setPsiBrief(String psiBrief) {
		this.psiBrief = psiBrief;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column project_start_view.PSI_REASON
	 * @return  the value of project_start_view.PSI_REASON
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public String getPsiReason() {
		return psiReason;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column project_start_view.PSI_REASON
	 * @param psiReason  the value for project_start_view.PSI_REASON
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public void setPsiReason(String psiReason) {
		this.psiReason = psiReason;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column project_start_view.PSI_CONTENT
	 * @return  the value of project_start_view.PSI_CONTENT
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public String getPsiContent() {
		return psiContent;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column project_start_view.PSI_CONTENT
	 * @param psiContent  the value for project_start_view.PSI_CONTENT
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public void setPsiContent(String psiContent) {
		this.psiContent = psiContent;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column project_start_view.PSI_FEATURE
	 * @return  the value of project_start_view.PSI_FEATURE
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public String getPsiFeature() {
		return psiFeature;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column project_start_view.PSI_FEATURE
	 * @param psiFeature  the value for project_start_view.PSI_FEATURE
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public void setPsiFeature(String psiFeature) {
		this.psiFeature = psiFeature;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column project_start_view.PSI_PLAN
	 * @return  the value of project_start_view.PSI_PLAN
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public String getPsiPlan() {
		return psiPlan;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column project_start_view.PSI_PLAN
	 * @param psiPlan  the value for project_start_view.PSI_PLAN
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public void setPsiPlan(String psiPlan) {
		this.psiPlan = psiPlan;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column project_start_view.PSI_RESULT
	 * @return  the value of project_start_view.PSI_RESULT
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public String getPsiResult() {
		return psiResult;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column project_start_view.PSI_RESULT
	 * @param psiResult  the value for project_start_view.PSI_RESULT
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public void setPsiResult(String psiResult) {
		this.psiResult = psiResult;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column project_start_view.U_ID
	 * @return  the value of project_start_view.U_ID
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public Integer getuId() {
		return uId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column project_start_view.U_ID
	 * @param uId  the value for project_start_view.U_ID
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public void setuId(Integer uId) {
		this.uId = uId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column project_start_view.U_TYPE
	 * @return  the value of project_start_view.U_TYPE
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public Integer getuType() {
		return uType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column project_start_view.U_TYPE
	 * @param uType  the value for project_start_view.U_TYPE
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public void setuType(Integer uType) {
		this.uType = uType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column project_start_view.PSI_O_STATUS
	 * @return  the value of project_start_view.PSI_O_STATUS
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public Integer getPsiOStatus() {
		return psiOStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column project_start_view.PSI_O_STATUS
	 * @param psiOStatus  the value for project_start_view.PSI_O_STATUS
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public void setPsiOStatus(Integer psiOStatus) {
		this.psiOStatus = psiOStatus;
	}
}