package com.plm.model;

import java.util.Date;

public class SiteFileInfo {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column site_file_info.SF_ID
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	private Integer sfId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column site_file_info.SF_TYPE
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	private Integer sfType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column site_file_info.SF_FROM
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	private Integer sfFrom;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column site_file_info.RELATED_ID
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	private Integer relatedId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column site_file_info.SF_NAME
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	private String sfName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column site_file_info.SF_SIZE
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	private Integer sfSize;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column site_file_info.SF_PATH
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	private String sfPath;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column site_file_info.SF_BRIEF
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	private String sfBrief;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column site_file_info.UP_TIME
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	private Date upTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column site_file_info.SF_ID
	 * @return  the value of site_file_info.SF_ID
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public Integer getSfId() {
		return sfId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column site_file_info.SF_ID
	 * @param sfId  the value for site_file_info.SF_ID
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public void setSfId(Integer sfId) {
		this.sfId = sfId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column site_file_info.SF_TYPE
	 * @return  the value of site_file_info.SF_TYPE
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public Integer getSfType() {
		return sfType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column site_file_info.SF_TYPE
	 * @param sfType  the value for site_file_info.SF_TYPE
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public void setSfType(Integer sfType) {
		this.sfType = sfType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column site_file_info.SF_FROM
	 * @return  the value of site_file_info.SF_FROM
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public Integer getSfFrom() {
		return sfFrom;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column site_file_info.SF_FROM
	 * @param sfFrom  the value for site_file_info.SF_FROM
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public void setSfFrom(Integer sfFrom) {
		this.sfFrom = sfFrom;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column site_file_info.RELATED_ID
	 * @return  the value of site_file_info.RELATED_ID
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public Integer getRelatedId() {
		return relatedId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column site_file_info.RELATED_ID
	 * @param relatedId  the value for site_file_info.RELATED_ID
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public void setRelatedId(Integer relatedId) {
		this.relatedId = relatedId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column site_file_info.SF_NAME
	 * @return  the value of site_file_info.SF_NAME
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public String getSfName() {
		return sfName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column site_file_info.SF_NAME
	 * @param sfName  the value for site_file_info.SF_NAME
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public void setSfName(String sfName) {
		this.sfName = sfName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column site_file_info.SF_SIZE
	 * @return  the value of site_file_info.SF_SIZE
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public Integer getSfSize() {
		return sfSize;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column site_file_info.SF_SIZE
	 * @param sfSize  the value for site_file_info.SF_SIZE
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public void setSfSize(Integer sfSize) {
		this.sfSize = sfSize;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column site_file_info.SF_PATH
	 * @return  the value of site_file_info.SF_PATH
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public String getSfPath() {
		return sfPath;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column site_file_info.SF_PATH
	 * @param sfPath  the value for site_file_info.SF_PATH
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public void setSfPath(String sfPath) {
		this.sfPath = sfPath;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column site_file_info.SF_BRIEF
	 * @return  the value of site_file_info.SF_BRIEF
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public String getSfBrief() {
		return sfBrief;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column site_file_info.SF_BRIEF
	 * @param sfBrief  the value for site_file_info.SF_BRIEF
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public void setSfBrief(String sfBrief) {
		this.sfBrief = sfBrief;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column site_file_info.UP_TIME
	 * @return  the value of site_file_info.UP_TIME
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public Date getUpTime() {
		return upTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column site_file_info.UP_TIME
	 * @param upTime  the value for site_file_info.UP_TIME
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public void setUpTime(Date upTime) {
		this.upTime = upTime;
	}
}