package com.plm.model;

import java.util.Date;

public class UserInfo {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_info.U_ID
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	private Integer uId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_info.U_NAME
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	private String uName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_info.U_REALNAME
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	private String uRealname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_info.Email
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	private String email;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_info.U_PASSWORD
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	private String uPassword;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_info.GENDER
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	private Integer gender;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_info.COLLEGE
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	private String college;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_info.MAJOR
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	private String major;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_info.TEL
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	private String tel;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_info.ADMISSION_DATE
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	private Date admissionDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_info.JOB_TITLE
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	private String jobTitle;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_info.ROLE
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	private Integer role;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_info.STATUS
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	private Integer status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_info.U_CODE
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	private String uCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_info.VALIDATA_CODE
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	private String validataCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_info.OUT_DATE
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	private Long outDate;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_info.U_ID
	 * @return  the value of user_info.U_ID
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public Integer getuId() {
		return uId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_info.U_ID
	 * @param uId  the value for user_info.U_ID
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public void setuId(Integer uId) {
		this.uId = uId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_info.U_NAME
	 * @return  the value of user_info.U_NAME
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public String getuName() {
		return uName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_info.U_NAME
	 * @param uName  the value for user_info.U_NAME
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public void setuName(String uName) {
		this.uName = uName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_info.U_REALNAME
	 * @return  the value of user_info.U_REALNAME
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public String getuRealname() {
		return uRealname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_info.U_REALNAME
	 * @param uRealname  the value for user_info.U_REALNAME
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public void setuRealname(String uRealname) {
		this.uRealname = uRealname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_info.Email
	 * @return  the value of user_info.Email
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public String getEmail() {
		return email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_info.Email
	 * @param email  the value for user_info.Email
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public void setEmail(String email) {
		this.email = email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_info.U_PASSWORD
	 * @return  the value of user_info.U_PASSWORD
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public String getuPassword() {
		return uPassword;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_info.U_PASSWORD
	 * @param uPassword  the value for user_info.U_PASSWORD
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public void setuPassword(String uPassword) {
		this.uPassword = uPassword;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_info.GENDER
	 * @return  the value of user_info.GENDER
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public Integer getGender() {
		return gender;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_info.GENDER
	 * @param gender  the value for user_info.GENDER
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public void setGender(Integer gender) {
		this.gender = gender;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_info.COLLEGE
	 * @return  the value of user_info.COLLEGE
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public String getCollege() {
		return college;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_info.COLLEGE
	 * @param college  the value for user_info.COLLEGE
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public void setCollege(String college) {
		this.college = college;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_info.MAJOR
	 * @return  the value of user_info.MAJOR
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public String getMajor() {
		return major;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_info.MAJOR
	 * @param major  the value for user_info.MAJOR
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public void setMajor(String major) {
		this.major = major;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_info.TEL
	 * @return  the value of user_info.TEL
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public String getTel() {
		return tel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_info.TEL
	 * @param tel  the value for user_info.TEL
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public void setTel(String tel) {
		this.tel = tel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_info.ADMISSION_DATE
	 * @return  the value of user_info.ADMISSION_DATE
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public Date getAdmissionDate() {
		return admissionDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_info.ADMISSION_DATE
	 * @param admissionDate  the value for user_info.ADMISSION_DATE
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public void setAdmissionDate(Date admissionDate) {
		this.admissionDate = admissionDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_info.JOB_TITLE
	 * @return  the value of user_info.JOB_TITLE
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public String getJobTitle() {
		return jobTitle;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_info.JOB_TITLE
	 * @param jobTitle  the value for user_info.JOB_TITLE
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public void setJobTitle(String jobTitle) {
		this.jobTitle = jobTitle;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_info.ROLE
	 * @return  the value of user_info.ROLE
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public Integer getRole() {
		return role;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_info.ROLE
	 * @param role  the value for user_info.ROLE
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public void setRole(Integer role) {
		this.role = role;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_info.STATUS
	 * @return  the value of user_info.STATUS
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public Integer getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_info.STATUS
	 * @param status  the value for user_info.STATUS
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public void setStatus(Integer status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_info.U_CODE
	 * @return  the value of user_info.U_CODE
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public String getuCode() {
		return uCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_info.U_CODE
	 * @param uCode  the value for user_info.U_CODE
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public void setuCode(String uCode) {
		this.uCode = uCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_info.VALIDATA_CODE
	 * @return  the value of user_info.VALIDATA_CODE
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public String getValidataCode() {
		return validataCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_info.VALIDATA_CODE
	 * @param validataCode  the value for user_info.VALIDATA_CODE
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public void setValidataCode(String validataCode) {
		this.validataCode = validataCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_info.OUT_DATE
	 * @return  the value of user_info.OUT_DATE
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public Long getOutDate() {
		return outDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_info.OUT_DATE
	 * @param outDate  the value for user_info.OUT_DATE
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public void setOutDate(Long outDate) {
		this.outDate = outDate;
	}

	@Override
	public String toString() {
		return "UserInfo [uId=" + uId + ", uName=" + uName + ", uRealname=" + uRealname + ", email=" + email
				+ ", uPassword=" + uPassword + ", gender=" + gender + ", college=" + college + ", major=" + major
				+ ", tel=" + tel + ", admissionDate=" + admissionDate + ", jobTitle=" + jobTitle + ", role=" + role
				+ ", status=" + status + ", uCode=" + uCode + ", validataCode=" + validataCode + ", outDate=" + outDate
				+ "]";
	}
	
}