package com.plm.model;

import java.util.Date;

public class WeeklyView {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column weekly_view.PB_ID
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	private Integer pbId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column weekly_view.W_ID
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	private Integer wId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column weekly_view.W_START_TIME
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	private Date wStartTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column weekly_view.W_END_TIME
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	private Date wEndTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column weekly_view.W_THIS_WEEK
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	private String wThisWeek;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column weekly_view.W_NEXT_WEEK
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	private String wNextWeek;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column weekly_view.W_STATUS
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	private Integer wStatus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column weekly_view.W_OPINION
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	private String wOpinion;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column weekly_view.PB_CREATE_TIME
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	private Date pbCreateTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column weekly_view.PB_EDIT_TIME
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	private Date pbEditTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column weekly_view.PB_NAME
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	private String pbName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column weekly_view.PB_LEVEL
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	private Integer pbLevel;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column weekly_view.PB_TYPE
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	private Integer pbType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column weekly_view.SUBJECT_TYPE
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	private Integer subjectType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column weekly_view.WS_STATUS
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	private Integer wsStatus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column weekly_view.U_ID
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	private Integer uId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column weekly_view.U_TYPE
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	private Integer uType;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column weekly_view.PB_ID
	 * @return  the value of weekly_view.PB_ID
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public Integer getPbId() {
		return pbId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column weekly_view.PB_ID
	 * @param pbId  the value for weekly_view.PB_ID
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public void setPbId(Integer pbId) {
		this.pbId = pbId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column weekly_view.W_ID
	 * @return  the value of weekly_view.W_ID
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public Integer getwId() {
		return wId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column weekly_view.W_ID
	 * @param wId  the value for weekly_view.W_ID
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public void setwId(Integer wId) {
		this.wId = wId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column weekly_view.W_START_TIME
	 * @return  the value of weekly_view.W_START_TIME
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public Date getwStartTime() {
		return wStartTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column weekly_view.W_START_TIME
	 * @param wStartTime  the value for weekly_view.W_START_TIME
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public void setwStartTime(Date wStartTime) {
		this.wStartTime = wStartTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column weekly_view.W_END_TIME
	 * @return  the value of weekly_view.W_END_TIME
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public Date getwEndTime() {
		return wEndTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column weekly_view.W_END_TIME
	 * @param wEndTime  the value for weekly_view.W_END_TIME
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public void setwEndTime(Date wEndTime) {
		this.wEndTime = wEndTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column weekly_view.W_THIS_WEEK
	 * @return  the value of weekly_view.W_THIS_WEEK
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public String getwThisWeek() {
		return wThisWeek;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column weekly_view.W_THIS_WEEK
	 * @param wThisWeek  the value for weekly_view.W_THIS_WEEK
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public void setwThisWeek(String wThisWeek) {
		this.wThisWeek = wThisWeek;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column weekly_view.W_NEXT_WEEK
	 * @return  the value of weekly_view.W_NEXT_WEEK
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public String getwNextWeek() {
		return wNextWeek;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column weekly_view.W_NEXT_WEEK
	 * @param wNextWeek  the value for weekly_view.W_NEXT_WEEK
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public void setwNextWeek(String wNextWeek) {
		this.wNextWeek = wNextWeek;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column weekly_view.W_STATUS
	 * @return  the value of weekly_view.W_STATUS
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public Integer getwStatus() {
		return wStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column weekly_view.W_STATUS
	 * @param wStatus  the value for weekly_view.W_STATUS
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public void setwStatus(Integer wStatus) {
		this.wStatus = wStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column weekly_view.W_OPINION
	 * @return  the value of weekly_view.W_OPINION
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public String getwOpinion() {
		return wOpinion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column weekly_view.W_OPINION
	 * @param wOpinion  the value for weekly_view.W_OPINION
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public void setwOpinion(String wOpinion) {
		this.wOpinion = wOpinion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column weekly_view.PB_CREATE_TIME
	 * @return  the value of weekly_view.PB_CREATE_TIME
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public Date getPbCreateTime() {
		return pbCreateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column weekly_view.PB_CREATE_TIME
	 * @param pbCreateTime  the value for weekly_view.PB_CREATE_TIME
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public void setPbCreateTime(Date pbCreateTime) {
		this.pbCreateTime = pbCreateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column weekly_view.PB_EDIT_TIME
	 * @return  the value of weekly_view.PB_EDIT_TIME
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public Date getPbEditTime() {
		return pbEditTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column weekly_view.PB_EDIT_TIME
	 * @param pbEditTime  the value for weekly_view.PB_EDIT_TIME
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public void setPbEditTime(Date pbEditTime) {
		this.pbEditTime = pbEditTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column weekly_view.PB_NAME
	 * @return  the value of weekly_view.PB_NAME
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public String getPbName() {
		return pbName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column weekly_view.PB_NAME
	 * @param pbName  the value for weekly_view.PB_NAME
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public void setPbName(String pbName) {
		this.pbName = pbName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column weekly_view.PB_LEVEL
	 * @return  the value of weekly_view.PB_LEVEL
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public Integer getPbLevel() {
		return pbLevel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column weekly_view.PB_LEVEL
	 * @param pbLevel  the value for weekly_view.PB_LEVEL
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public void setPbLevel(Integer pbLevel) {
		this.pbLevel = pbLevel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column weekly_view.PB_TYPE
	 * @return  the value of weekly_view.PB_TYPE
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public Integer getPbType() {
		return pbType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column weekly_view.PB_TYPE
	 * @param pbType  the value for weekly_view.PB_TYPE
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public void setPbType(Integer pbType) {
		this.pbType = pbType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column weekly_view.SUBJECT_TYPE
	 * @return  the value of weekly_view.SUBJECT_TYPE
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public Integer getSubjectType() {
		return subjectType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column weekly_view.SUBJECT_TYPE
	 * @param subjectType  the value for weekly_view.SUBJECT_TYPE
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public void setSubjectType(Integer subjectType) {
		this.subjectType = subjectType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column weekly_view.WS_STATUS
	 * @return  the value of weekly_view.WS_STATUS
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public Integer getWsStatus() {
		return wsStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column weekly_view.WS_STATUS
	 * @param wsStatus  the value for weekly_view.WS_STATUS
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public void setWsStatus(Integer wsStatus) {
		this.wsStatus = wsStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column weekly_view.U_ID
	 * @return  the value of weekly_view.U_ID
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public Integer getuId() {
		return uId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column weekly_view.U_ID
	 * @param uId  the value for weekly_view.U_ID
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public void setuId(Integer uId) {
		this.uId = uId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column weekly_view.U_TYPE
	 * @return  the value of weekly_view.U_TYPE
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public Integer getuType() {
		return uType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column weekly_view.U_TYPE
	 * @param uType  the value for weekly_view.U_TYPE
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public void setuType(Integer uType) {
		this.uType = uType;
	}
}