package com.plm.model;

import java.util.Date;

public class WeeklyInfo {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column weekly_info.W_ID
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	private Integer wId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column weekly_info.PB_ID
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	private Integer pbId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column weekly_info.W_START_TIME
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	private Date wStartTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column weekly_info.W_END_TIME
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	private Date wEndTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column weekly_info.W_THIS_WEEK
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	private String wThisWeek;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column weekly_info.W_NEXT_WEEK
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	private String wNextWeek;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column weekly_info.W_STATUS
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	private Integer wStatus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column weekly_info.W_OPINION
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	private String wOpinion;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column weekly_info.W_ID
	 * @return  the value of weekly_info.W_ID
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public Integer getwId() {
		return wId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column weekly_info.W_ID
	 * @param wId  the value for weekly_info.W_ID
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public void setwId(Integer wId) {
		this.wId = wId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column weekly_info.PB_ID
	 * @return  the value of weekly_info.PB_ID
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public Integer getPbId() {
		return pbId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column weekly_info.PB_ID
	 * @param pbId  the value for weekly_info.PB_ID
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public void setPbId(Integer pbId) {
		this.pbId = pbId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column weekly_info.W_START_TIME
	 * @return  the value of weekly_info.W_START_TIME
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public Date getwStartTime() {
		return wStartTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column weekly_info.W_START_TIME
	 * @param wStartTime  the value for weekly_info.W_START_TIME
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public void setwStartTime(Date wStartTime) {
		this.wStartTime = wStartTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column weekly_info.W_END_TIME
	 * @return  the value of weekly_info.W_END_TIME
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public Date getwEndTime() {
		return wEndTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column weekly_info.W_END_TIME
	 * @param wEndTime  the value for weekly_info.W_END_TIME
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public void setwEndTime(Date wEndTime) {
		this.wEndTime = wEndTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column weekly_info.W_THIS_WEEK
	 * @return  the value of weekly_info.W_THIS_WEEK
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public String getwThisWeek() {
		return wThisWeek;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column weekly_info.W_THIS_WEEK
	 * @param wThisWeek  the value for weekly_info.W_THIS_WEEK
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public void setwThisWeek(String wThisWeek) {
		this.wThisWeek = wThisWeek;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column weekly_info.W_NEXT_WEEK
	 * @return  the value of weekly_info.W_NEXT_WEEK
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public String getwNextWeek() {
		return wNextWeek;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column weekly_info.W_NEXT_WEEK
	 * @param wNextWeek  the value for weekly_info.W_NEXT_WEEK
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public void setwNextWeek(String wNextWeek) {
		this.wNextWeek = wNextWeek;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column weekly_info.W_STATUS
	 * @return  the value of weekly_info.W_STATUS
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public Integer getwStatus() {
		return wStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column weekly_info.W_STATUS
	 * @param wStatus  the value for weekly_info.W_STATUS
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public void setwStatus(Integer wStatus) {
		this.wStatus = wStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column weekly_info.W_OPINION
	 * @return  the value of weekly_info.W_OPINION
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public String getwOpinion() {
		return wOpinion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column weekly_info.W_OPINION
	 * @param wOpinion  the value for weekly_info.W_OPINION
	 * @mbg.generated  Tue May 15 22:59:52 CST 2018
	 */
	public void setwOpinion(String wOpinion) {
		this.wOpinion = wOpinion;
	}
}